//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: `apipe pretty` reads NDJSON, emits a human-readable table to stdout. Columns: kind, id, ts, subject, score, plus a one-line snippet of payload. Width-aware: truncates long fields with `…`. Output is line-oriented but NOT NDJSON; pretty is a sink stage (don't chain after it).
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

const REC: &str = r#"{"kind":"recall_hit","source":"recall:01","id":"01","ts":"2026-05-22T00:00:00Z","subject":"self","score":3.14,"payload":{"x":1}}"#;

#[test]
fn acceptance_ac7() {
    let bin = env!("CARGO_BIN_EXE_apipe");
    let input = format!("{REC}\n");
    let mut child = Command::new(bin)
        .arg("pretty")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    assert!(lines.len() >= 2, "expected header + at least one row: {stdout}");
    assert!(lines[0].contains("kind"));
    assert!(lines[0].contains("score"));
    assert!(stdout.contains("recall_hit") && stdout.contains("self"));
    assert!(serde_json::from_str::<serde_json::Value>(lines[0]).is_err());
}
