//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: Malformed JSON lines on input (parse error, not just missing required fields) are reported to stderr with line number, record dropped, processing continues. The pipeline does not abort on a single malformed line.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

#[test]
fn acceptance_ac10() {
    let good = r#"{"kind":"recall_hit","source":"recall:a","id":"a","ts":"2026-05-22T00:00:00Z"}"#;
    let malformed = "{not json at all";
    let good2 = r#"{"kind":"file_event","source":"fsstory:/x","id":"b","ts":"2026-05-22T00:00:00Z"}"#;
    let input = format!("{good}\n{malformed}\n{good2}\n");

    let bin = env!("CARGO_BIN_EXE_apipe");
    let mut child = Command::new(bin)
        .arg("pass")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let stderr = String::from_utf8(out.stderr).unwrap();
    assert!(stdout.contains("\"id\":\"a\""));
    assert!(stdout.contains("\"id\":\"b\""));
    assert!(stderr.contains("line 2"));
}
