//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: `apipe schema` (no args) prints the list of known record kinds to stdout, one per line. `apipe schema --kind <name>` prints the JSON Schema for that kind. Unknown kind → exit 2 with stderr diagnostic.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

#[test]
fn acceptance_ac5() {
    let bin = env!("CARGO_BIN_EXE_apipe");

    // No args: list known kinds.
    let out = Command::new(bin).arg("schema").output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    for k in ["recall_hit", "transcript_turn", "file_event"] {
        assert!(stdout.contains(k), "missing kind in list: {k}");
    }

    // --kind <known>: print JSON Schema.
    let out = Command::new(bin)
        .args(["schema", "--kind", "recall_hit"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let parsed: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(parsed["$id"], "agent_pipe.recall_hit.v1");

    // --kind <unknown>: exit 2.
    let out = Command::new(bin)
        .args(["schema", "--kind", "nonexistent_kind"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
    let stderr = String::from_utf8(out.stderr).unwrap();
    assert!(!stderr.is_empty());
}
