//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: `apipe top N` reads NDJSON, emits up to N records with the highest `score` (default field). `--by <field>` selects a different numeric field. Stable for ties (preserves input order). Streaming with bounded memory: maintains a min-heap of size N rather than buffering all input.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

fn record(id: &str, score: f64) -> String {
    format!(
        r#"{{"kind":"recall_hit","source":"recall:{id}","id":"{id}","ts":"2026-05-22T00:00:00Z","score":{score}}}"#
    )
}

#[test]
fn acceptance_ac3() {
    let input = vec![
        record("a", 0.1),
        record("b", 0.9),
        record("c", 0.5),
        record("d", 0.9),
        record("e", 0.3),
    ]
    .join("\n")
        + "\n";

    let bin = env!("CARGO_BIN_EXE_apipe");
    let mut child = Command::new(bin)
        .args(["top", "2"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    assert_eq!(lines.len(), 2);
    assert!(lines[0].contains("\"id\":\"b\""));
    assert!(lines[1].contains("\"id\":\"d\""));
}
