//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: `apipe sort -k <field>` reads all NDJSON into memory, emits records sorted ascending by `<field>` (numeric if all values are numeric, else lexicographic). `--desc` reverses. Sort is stable.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

fn record(id: &str, score: f64) -> String {
    format!(
        r#"{{"kind":"recall_hit","source":"recall:{id}","id":"{id}","ts":"2026-05-22T00:00:00Z","score":{score}}}"#
    )
}

fn run_sort(args: &[&str], input: &str) -> std::process::Output {
    let bin = env!("CARGO_BIN_EXE_apipe");
    let mut cmd = Command::new(bin);
    cmd.arg("sort");
    for a in args {
        cmd.arg(a);
    }
    let mut child = cmd
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    child.wait_with_output().unwrap()
}

#[test]
fn acceptance_ac4() {
    let input = vec![record("c", 0.5), record("a", 0.1), record("b", 0.3)].join("\n") + "\n";

    let asc = run_sort(&["-k", "score"], &input);
    let stdout = String::from_utf8(asc.stdout).unwrap();
    let order: Vec<&str> = stdout
        .lines()
        .map(|l| {
            if l.contains("\"id\":\"a\"") {
                "a"
            } else if l.contains("\"id\":\"b\"") {
                "b"
            } else {
                "c"
            }
        })
        .collect();
    assert_eq!(order, vec!["a", "b", "c"]);

    let desc = run_sort(&["-k", "score", "--desc"], &input);
    let stdout = String::from_utf8(desc.stdout).unwrap();
    let order: Vec<&str> = stdout
        .lines()
        .map(|l| {
            if l.contains("\"id\":\"a\"") {
                "a"
            } else if l.contains("\"id\":\"b\"") {
                "b"
            } else {
                "c"
            }
        })
        .collect();
    assert_eq!(order, vec!["c", "b", "a"]);
}
