//! Acceptance test for AC9 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: `apipe from-paths` reads bare path strings, emits file_event records with `payload.path` set. Stable id derived from `sha256(path)[..12]`, `ts` set to file mtime if the file exists, else current time.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

#[test]
fn acceptance_ac9() {
    let input = "/tmp/foo.md\n/var/log/bar.txt\n";
    let bin = env!("CARGO_BIN_EXE_apipe");
    let mut child = Command::new(bin)
        .arg("from-paths")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    assert_eq!(lines.len(), 2);
    for line in &lines {
        let v: serde_json::Value = serde_json::from_str(line).unwrap();
        assert_eq!(v["kind"], "file_event");
        assert!(v["id"].is_string());
        assert!(v["ts"].is_string());
    }
    let v1: serde_json::Value = serde_json::from_str(lines[0]).unwrap();
    let id1 = v1["id"].as_str().unwrap().to_string();

    let mut child2 = Command::new(bin)
        .arg("from-paths")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child2.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child2.stdin.take());
    let out2 = child2.wait_with_output().unwrap();
    let stdout2 = String::from_utf8(out2.stdout).unwrap();
    let v2: serde_json::Value = serde_json::from_str(stdout2.lines().next().unwrap()).unwrap();
    assert_eq!(v2["id"].as_str().unwrap(), id1);
}
