//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: `apipe filter <expr>` keeps records where `<expr>` evaluates true. `<expr>` is a minimal predicate language: `<field> <op> <literal>` with ops `==`, `!=`, `<`, `<=`, `>`, `>=`, `~` (substring). String literals quoted; numeric literals bare. Example: `apipe filter 'score > 0.8'`.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

fn record(id: &str, kind: &str, score: f64) -> String {
    format!(
        r#"{{"kind":"{kind}","source":"recall:{id}","id":"{id}","ts":"2026-05-22T00:00:00Z","score":{score}}}"#
    )
}

fn run_filter(expr: &str, input: &str) -> std::process::Output {
    let bin = env!("CARGO_BIN_EXE_apipe");
    let mut child = Command::new(bin)
        .args(["filter", expr])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    child.wait_with_output().unwrap()
}

#[test]
fn acceptance_ac6() {
    let input = vec![
        record("a", "recall_hit", 0.1),
        record("b", "file_event", 0.9),
        record("c", "recall_hit", 0.5),
    ]
    .join("\n")
        + "\n";

    let out = run_filter("score > 0.4", &input);
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert!(!stdout.contains("\"id\":\"a\""));
    assert!(stdout.contains("\"id\":\"b\""));
    assert!(stdout.contains("\"id\":\"c\""));

    let out = run_filter("kind == \"file_event\"", &input);
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert!(!stdout.contains("\"id\":\"a\""));
    assert!(stdout.contains("\"id\":\"b\""));
    assert!(!stdout.contains("\"id\":\"c\""));
}
