//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: Every record must have required fields `kind`, `source`, `id`, `ts`. `apipe pass` (and every other subcommand) validates each input line; missing required fields → write the original line + an error message to stderr with the 1-indexed line number, drop the record, continue processing. Exit 0 if any records passed through; exit 1 if no input was valid.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

fn run_pass(input: &str) -> std::process::Output {
    let bin = env!("CARGO_BIN_EXE_apipe");
    let mut child = Command::new(bin)
        .arg("pass")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    child.wait_with_output().unwrap()
}

#[test]
fn acceptance_ac2_missing_required_field_dropped() {
    // Missing `ts` field.
    let bad = r#"{"kind":"recall_hit","source":"recall:01","id":"01"}"#;
    let good = r#"{"kind":"file_event","source":"fsstory:/y","id":"y","ts":"2026-05-22T00:00:00Z"}"#;
    let out = run_pass(&format!("{bad}\n{good}\n"));
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let stderr = String::from_utf8(out.stderr).unwrap();
    assert!(stdout.contains(good), "good record must pass through");
    assert!(!stdout.contains(bad), "bad record must be dropped");
    assert!(stderr.contains("line 1"), "stderr must reference line 1 of the bad record");
    assert!(stderr.contains("ts"), "stderr must name the missing field");
}

#[test]
fn acceptance_ac2_no_valid_input_exits_1() {
    let bad_only = r#"{"kind":"foo","source":"x","id":"y"}"#; // missing ts
    let out = run_pass(&format!("{bad_only}\n"));
    assert_eq!(out.status.code(), Some(1), "exit 1 when no input is valid");
}
