//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agent-pipe (cli)
//! AC description: `apipe to-paths` reads NDJSON, emits bare path strings (one per line) extracted from records of kind=file_event (from `payload.path`) or any record with a top-level `payload.path` field. Non-matching records dropped silently. Escape hatch back to shell `xargs`-style usage.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};

#[test]
fn acceptance_ac8() {
    let with_path = r#"{"kind":"file_event","source":"fsstory:/a","id":"a","ts":"2026-05-22T00:00:00Z","payload":{"path":"/tmp/a.md"}}"#;
    let no_path = r#"{"kind":"recall_hit","source":"recall:b","id":"b","ts":"2026-05-22T00:00:00Z"}"#;
    let with_path_2 = r#"{"kind":"file_event","source":"fsstory:/c","id":"c","ts":"2026-05-22T00:00:00Z","payload":{"path":"/etc/x"}}"#;
    let input = format!("{with_path}\n{no_path}\n{with_path_2}\n");

    let bin = env!("CARGO_BIN_EXE_apipe");
    let mut child = Command::new(bin)
        .arg("to-paths")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(input.as_bytes()).unwrap();
    drop(child.stdin.take());
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    assert_eq!(lines, vec!["/tmp/a.md", "/etc/x"]);
}
