//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: `primary_author` is the author whose commits touching the file outnumber any other author's commits on it. Ties break by most recent commit. Author identity is the commit author name (not email).
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Oid, Repository, Signature, Time};
use tempfile::TempDir;

fn commit_as(repo: &Repository, dir: &Path, name: &str, body: &str, author: &str, when: i64, parents: &[Oid]) -> Oid {
    fs::write(dir.join(name), body).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(Path::new(name)).unwrap();
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new(author, "x@example.com", &Time::new(when, 0)).unwrap();
    let parents_commits: Vec<git2::Commit<'_>> = parents.iter().map(|p| repo.find_commit(*p).unwrap()).collect();
    let parent_refs: Vec<&git2::Commit<'_>> = parents_commits.iter().collect();
    repo.commit(Some("HEAD"), &sig, &sig, "msg", &tree, &parent_refs).unwrap()
}

#[test]
fn acceptance_ac4() {
    let tmp = TempDir::new().unwrap();
    let repo = Repository::init(tmp.path()).unwrap();

    // a.rs: Alice 3 commits, Bob 1 commit -> Alice wins by count.
    let c1 = commit_as(&repo, tmp.path(), "a.rs", "1\n", "Alice", 1_700_000_000, &[]);
    let c2 = commit_as(&repo, tmp.path(), "a.rs", "2\n", "Alice", 1_700_000_100, &[c1]);
    let c3 = commit_as(&repo, tmp.path(), "a.rs", "3\n", "Bob",   1_700_000_200, &[c2]);
    let c4 = commit_as(&repo, tmp.path(), "a.rs", "4\n", "Alice", 1_700_000_300, &[c3]);

    // b.rs: tie (2 each), Bob's last commit is more recent -> Bob wins tiebreak.
    let c5 = commit_as(&repo, tmp.path(), "b.rs", "1\n", "Alice", 1_700_000_400, &[c4]);
    let c6 = commit_as(&repo, tmp.path(), "b.rs", "2\n", "Bob",   1_700_000_500, &[c5]);
    let c7 = commit_as(&repo, tmp.path(), "b.rs", "3\n", "Alice", 1_700_000_600, &[c6]);
    let _c8 = commit_as(&repo, tmp.path(), "b.rs", "4\n", "Bob",  1_700_000_700, &[c7]);

    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out = Command::new(bin).args(["walk", "--repo"]).arg(tmp.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let files = parsed["files"].as_array().unwrap();
    let a = files.iter().find(|f| f["path"] == "a.rs").unwrap();
    assert_eq!(a["primary_author"], "Alice", "majority rules");
    let b = files.iter().find(|f| f["path"] == "b.rs").unwrap();
    assert_eq!(b["primary_author"], "Bob", "tie broken by most recent commit");
}
