//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: `--summary` flag prints (to stderr) a one-line summary per language: `<lang>: <file-count> files, <total-commits> commits` before the main JSON. Default JSON output on stdout is unaffected.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature, Time};
use tempfile::TempDir;

#[test]
fn acceptance_ac7() {
    let tmp = TempDir::new().unwrap();
    let repo = Repository::init(tmp.path()).unwrap();

    fs::write(tmp.path().join("a.rs"), "1\n").unwrap();
    fs::write(tmp.path().join("b.rs"), "2\n").unwrap();
    fs::write(tmp.path().join("c.md"), "3\n").unwrap();
    let mut index = repo.index().unwrap();
    for p in &["a.rs", "b.rs", "c.md"] {
        index.add_path(Path::new(p)).unwrap();
    }
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Author", "a@example.com", &Time::new(1_700_000_000, 0)).unwrap();
    repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[]).unwrap();

    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out_plain = Command::new(bin).args(["walk", "--repo"]).arg(tmp.path()).output().unwrap();
    assert_eq!(out_plain.status.code(), Some(0));

    let out = Command::new(bin).args(["walk", "--summary", "--repo"]).arg(tmp.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("Rust: 2 files, 2 commits"), "got stderr: {stderr}");
    assert!(stderr.contains("Markdown: 1 files, 1 commits"), "got stderr: {stderr}");

    // Stdout JSON must be unaffected (identical structure to plain run).
    let parsed_plain: serde_json::Value = serde_json::from_slice(&out_plain.stdout).unwrap();
    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let files_plain = parsed_plain["files"].as_array().unwrap();
    let files = parsed["files"].as_array().unwrap();
    assert_eq!(files_plain.len(), files.len());
    for (a, b) in files_plain.iter().zip(files.iter()) {
        assert_eq!(a["path"], b["path"]);
        assert_eq!(a["language"], b["language"]);
        assert_eq!(a["commit_count"], b["commit_count"]);
    }
}
