//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: Files matched by `.gitignore` are excluded from the output (we walk the index/HEAD, not the working tree). Untracked files do not appear.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::collections::HashSet;
use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature, Time};
use tempfile::TempDir;

#[test]
fn acceptance_ac6() {
    let tmp = TempDir::new().unwrap();
    let repo = Repository::init(tmp.path()).unwrap();

    // Tracked file.
    fs::write(tmp.path().join("kept.rs"), "fn main() {}\n").unwrap();
    // .gitignore (tracked) ignoring target/ and *.log.
    fs::write(tmp.path().join(".gitignore"), "target/\n*.log\n").unwrap();
    // Untracked file that exists on disk but is never added.
    fs::write(tmp.path().join("untracked.rs"), "// untracked\n").unwrap();
    // Working-tree-only file matched by gitignore.
    fs::create_dir_all(tmp.path().join("target")).unwrap();
    fs::write(tmp.path().join("target").join("ignored.rs"), "ignored\n").unwrap();
    fs::write(tmp.path().join("debug.log"), "log\n").unwrap();

    let mut index = repo.index().unwrap();
    index.add_path(Path::new("kept.rs")).unwrap();
    index.add_path(Path::new(".gitignore")).unwrap();
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Author", "a@example.com", &Time::new(1_700_000_000, 0)).unwrap();
    repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[]).unwrap();

    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out = Command::new(bin).args(["walk", "--repo"]).arg(tmp.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let files = parsed["files"].as_array().unwrap();
    let paths: HashSet<String> = files.iter().map(|f| f["path"].as_str().unwrap().to_string()).collect();

    assert!(paths.contains("kept.rs"), "tracked file must appear");
    assert!(paths.contains(".gitignore"), "tracked .gitignore must appear");
    assert!(!paths.contains("untracked.rs"), "untracked file must not appear");
    assert!(!paths.contains("target/ignored.rs"), "gitignored file must not appear");
    assert!(!paths.contains("debug.log"), "gitignored file must not appear");
}
