//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: `repo-as-landscape walk --repo <git-dir>` emits a single JSON object on stdout. Top-level: `{"repo": "<absolute path>", "generated_at": "<RFC3339>", "files": [...]}`. Each file entry is `{"path": "<repo-relative>", "language": "<lang>", "commit_count": <u32>, "last_touched": "<RFC3339>", "primary_author": "<name>", "size_bytes": <u64>}`. Exits 0 on success.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature};
use tempfile::TempDir;

fn init_repo_with_one_file(dir: &Path) {
    let repo = Repository::init(dir).unwrap();
    fs::write(dir.join("README.md"), b"hello\n").unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(Path::new("README.md")).unwrap();
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Alice", "alice@example.com", &git2::Time::new(1_700_000_000, 0)).unwrap();
    repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[]).unwrap();
}

#[test]
fn acceptance_ac1() {
    let tmp = TempDir::new().unwrap();
    init_repo_with_one_file(tmp.path());

    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out = Command::new(bin)
        .args(["walk", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let repo_field = parsed["repo"].as_str().unwrap();
    assert!(Path::new(repo_field).is_absolute(), "repo field must be absolute: {repo_field}");
    assert!(parsed["generated_at"].is_string());
    // RFC3339 sanity: parse it.
    chrono::DateTime::parse_from_rfc3339(parsed["generated_at"].as_str().unwrap()).unwrap();

    let files = parsed["files"].as_array().unwrap();
    assert_eq!(files.len(), 1);
    let f = &files[0];
    assert_eq!(f["path"], "README.md");
    assert_eq!(f["language"], "Markdown");
    assert!(f["commit_count"].is_u64());
    assert_eq!(f["commit_count"].as_u64().unwrap(), 1);
    assert!(f["last_touched"].is_string());
    chrono::DateTime::parse_from_rfc3339(f["last_touched"].as_str().unwrap()).unwrap();
    assert_eq!(f["primary_author"], "Alice");
    assert!(f["size_bytes"].is_u64());
    assert_eq!(f["size_bytes"].as_u64().unwrap(), 6);
}
