//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: Language detection covers at least: Rust (.rs), Python (.py), TypeScript (.ts/.tsx), JavaScript (.js/.jsx), Markdown (.md), JSON (.json), TOML (.toml), Shell (.sh/.bash/.zsh), YAML (.yml/.yaml), HTML (.html), CSS (.css), Go (.go), C (.c/.h), C++ (.cpp/.hpp), Java (.java). Files without a known extension get `"language": "unknown"`.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature};
use tempfile::TempDir;

const FIXTURES: &[(&str, &str)] = &[
    ("a.rs", "Rust"),
    ("b.py", "Python"),
    ("c.ts", "TypeScript"),
    ("d.tsx", "TypeScript"),
    ("e.js", "JavaScript"),
    ("f.jsx", "JavaScript"),
    ("g.md", "Markdown"),
    ("h.json", "JSON"),
    ("i.toml", "TOML"),
    ("j.sh", "Shell"),
    ("k.bash", "Shell"),
    ("l.zsh", "Shell"),
    ("m.yml", "YAML"),
    ("n.yaml", "YAML"),
    ("o.html", "HTML"),
    ("p.css", "CSS"),
    ("q.go", "Go"),
    ("r.c", "C"),
    ("s.h", "C"),
    ("t.cpp", "C++"),
    ("u.hpp", "C++"),
    ("v.java", "Java"),
    ("Makefile", "unknown"),
    ("README", "unknown"),
];

#[test]
fn acceptance_ac2() {
    let tmp = TempDir::new().unwrap();
    let repo = Repository::init(tmp.path()).unwrap();
    let mut index = repo.index().unwrap();
    for (name, _) in FIXTURES {
        fs::write(tmp.path().join(name), b"x\n").unwrap();
        index.add_path(Path::new(name)).unwrap();
    }
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Author", "a@example.com", &git2::Time::new(1_700_000_000, 0)).unwrap();
    repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[]).unwrap();

    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out = Command::new(bin).args(["walk", "--repo"]).arg(tmp.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let files = parsed["files"].as_array().unwrap();
    let mut by_path: HashMap<String, String> = HashMap::new();
    for f in files {
        by_path.insert(f["path"].as_str().unwrap().to_string(), f["language"].as_str().unwrap().to_string());
    }
    for (name, expected) in FIXTURES {
        assert_eq!(by_path.get(*name).map(String::as_str), Some(*expected), "mismatch for {name}");
    }
}
