//! Acceptance test for AC8 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: `--coalesce-below <N>` collapses any directory containing fewer than N tracked files into a single synthetic file entry `{path: "<dir>/.", language: "directory", commit_count: sum_of_children, ...}` so deep trees stay legible.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature, Time};
use tempfile::TempDir;

#[test]
fn acceptance_ac8() {
    let tmp = TempDir::new().unwrap();
    let repo = Repository::init(tmp.path()).unwrap();

    // Layout:
    //   big/    -> 3 files (above threshold of 3 -> not coalesced)
    //   small/  -> 1 file  (below threshold -> coalesced)
    //   tiny/   -> 2 files (below threshold -> coalesced)
    //   root.md -> not under any dir (parent is empty -> not coalesced)
    fs::create_dir_all(tmp.path().join("big")).unwrap();
    fs::create_dir_all(tmp.path().join("small")).unwrap();
    fs::create_dir_all(tmp.path().join("tiny")).unwrap();
    fs::write(tmp.path().join("big/a.rs"), "a\n").unwrap();
    fs::write(tmp.path().join("big/b.rs"), "b\n").unwrap();
    fs::write(tmp.path().join("big/c.rs"), "c\n").unwrap();
    fs::write(tmp.path().join("small/only.rs"), "only\n").unwrap();
    fs::write(tmp.path().join("tiny/x.rs"), "x\n").unwrap();
    fs::write(tmp.path().join("tiny/y.rs"), "y\n").unwrap();
    fs::write(tmp.path().join("root.md"), "r\n").unwrap();

    let mut index = repo.index().unwrap();
    for p in &[
        "big/a.rs", "big/b.rs", "big/c.rs",
        "small/only.rs",
        "tiny/x.rs", "tiny/y.rs",
        "root.md",
    ] {
        index.add_path(Path::new(p)).unwrap();
    }
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Author", "a@example.com", &Time::new(1_700_000_000, 0)).unwrap();
    repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[]).unwrap();

    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out = Command::new(bin)
        .args(["walk", "--coalesce-below", "3", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let files = parsed["files"].as_array().unwrap();
    let by_path: HashMap<String, &serde_json::Value> = files
        .iter()
        .map(|f| (f["path"].as_str().unwrap().to_string(), f))
        .collect();

    // big/ is above threshold; its files remain.
    assert!(by_path.contains_key("big/a.rs"));
    assert!(by_path.contains_key("big/b.rs"));
    assert!(by_path.contains_key("big/c.rs"));

    // small/ has 1 file -> coalesced.
    let small = by_path.get("small/.").expect("small/. must exist as synthetic entry");
    assert_eq!(small["language"], "directory");
    assert_eq!(small["commit_count"].as_u64().unwrap(), 1);
    assert!(!by_path.contains_key("small/only.rs"));

    // tiny/ has 2 files -> coalesced; commit_count is sum (1+1).
    let tiny = by_path.get("tiny/.").expect("tiny/. must exist as synthetic entry");
    assert_eq!(tiny["language"], "directory");
    assert_eq!(tiny["commit_count"].as_u64().unwrap(), 2);
    assert!(!by_path.contains_key("tiny/x.rs"));
    assert!(!by_path.contains_key("tiny/y.rs"));

    // root.md at repo root — never coalesced (parent dir is "").
    assert!(by_path.contains_key("root.md"));
}
