//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: `commit_count` counts the number of commits touching the file across the full reachable history of HEAD (equivalent to `git log --follow --oneline -- <path> | wc -l`). `last_touched` is the committer date of the most recent such commit.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use chrono::{DateTime, TimeZone, Utc};
use git2::{Oid, Repository, Signature, Time};
use tempfile::TempDir;

fn commit_file(repo: &Repository, dir: &Path, name: &str, body: &str, msg: &str, when: i64, parents: &[Oid]) -> Oid {
    fs::write(dir.join(name), body).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(Path::new(name)).unwrap();
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Author", "a@example.com", &Time::new(when, 0)).unwrap();
    let parents_commits: Vec<git2::Commit<'_>> = parents.iter().map(|p| repo.find_commit(*p).unwrap()).collect();
    let parent_refs: Vec<&git2::Commit<'_>> = parents_commits.iter().collect();
    repo.commit(Some("HEAD"), &sig, &sig, msg, &tree, &parent_refs).unwrap()
}

#[test]
fn acceptance_ac3() {
    let tmp = TempDir::new().unwrap();
    let repo = Repository::init(tmp.path()).unwrap();

    let c1 = commit_file(&repo, tmp.path(), "a.rs", "v1\n", "c1: add a", 1_700_000_000, &[]);
    // Touch b.rs in a separate commit (not a.rs).
    let c2 = commit_file(&repo, tmp.path(), "b.rs", "b1\n", "c2: add b", 1_700_000_100, &[c1]);
    // Touch a.rs three more times across history.
    let c3 = commit_file(&repo, tmp.path(), "a.rs", "v2\n", "c3: edit a", 1_700_000_200, &[c2]);
    let c4 = commit_file(&repo, tmp.path(), "a.rs", "v3\n", "c4: edit a", 1_700_000_300, &[c3]);
    let last_a = 1_700_000_400_i64;
    let _c5 = commit_file(&repo, tmp.path(), "a.rs", "v4\n", "c5: edit a", last_a, &[c4]);

    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out = Command::new(bin).args(["walk", "--repo"]).arg(tmp.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let files = parsed["files"].as_array().unwrap();
    let a = files.iter().find(|f| f["path"] == "a.rs").unwrap();
    assert_eq!(a["commit_count"].as_u64().unwrap(), 4, "a.rs touched in c1, c3, c4, c5");
    let last: DateTime<chrono::FixedOffset> = chrono::DateTime::parse_from_rfc3339(a["last_touched"].as_str().unwrap()).unwrap();
    let expected = Utc.timestamp_opt(last_a, 0).single().unwrap();
    assert_eq!(last.with_timezone(&Utc), expected);

    let b = files.iter().find(|f| f["path"] == "b.rs").unwrap();
    assert_eq!(b["commit_count"].as_u64().unwrap(), 1, "b.rs touched only in c2");
}
