//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: repo-as-landscape (cli)
//! AC description: Running against a non-git path exits with code 2 and stderr containing the path and `not a git repository`.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

use tempfile::TempDir;

#[test]
fn acceptance_ac5() {
    let tmp = TempDir::new().unwrap();
    // tmp is a plain empty directory — not a git repo.
    let bin = env!("CARGO_BIN_EXE_repo-as-landscape");
    let out = Command::new(bin).args(["walk", "--repo"]).arg(tmp.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(2));
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("not a git repository"), "stderr: {stderr}");
    assert!(stderr.contains(tmp.path().to_str().unwrap()), "stderr must contain the path; got: {stderr}");
}
