//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: The bundle format: each memory is a section separated by `\n---\n` lines. Each section starts with a YAML frontmatter block (id, kind, subject, recall_count, last_recalled_at, created_at), then a blank line, then the memory's Markdown body verbatim. The bundle starts with a top-level frontmatter block (year, generated_at, memory_count, recall_root) before the first separator.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

mod common;
use common::{FakeMemory, stage_recall_root};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac2() {
    let tmp = TempDir::new().unwrap();
    let mems = [
        FakeMemory {
            id: "01KS00000000000000000FORMAT",
            kind: "feedback",
            subject: "user",
            created_at: "2026-02-02T02:02:02Z",
            recall_count: 7,
            last_recalled_at: Some("2026-05-05T05:05:05Z"),
            private: false,
            body: "Body paragraph one.\n\nBody paragraph two.\n",
        },
    ];
    let (root, recall_cmd) = stage_recall_root(tmp.path(), &mems);

    let bin = env!("CARGO_BIN_EXE_reliquary");
    let out = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&recall_cmd)
        .output()
        .unwrap();
    assert!(out.status.success(), "stderr={}", String::from_utf8_lossy(&out.stderr));
    let bundle = String::from_utf8(out.stdout).unwrap();

    // Top-level frontmatter must appear first.
    assert!(bundle.starts_with("---\n"), "missing leading ---: {bundle}");
    let after_open = &bundle[4..];
    let close_idx = after_open.find("\n---\n").expect("missing top close ---");
    let top_fm = &after_open[..close_idx];
    for field in ["year:", "generated_at:", "memory_count:", "recall_root:"] {
        assert!(top_fm.contains(field), "top fm missing {field}: {top_fm}");
    }

    // The per-memory section follows the top close.
    let after_top = &after_open[close_idx + "\n---\n".len()..];
    // It should contain another --- block with id/kind/subject/etc.
    for field in [
        "id: 01KS00000000000000000FORMAT",
        "kind: feedback",
        "subject: user",
        "recall_count: 7",
        "last_recalled_at: \"2026-05-05T05:05:05Z\"",
        "created_at: \"2026-02-02T02:02:02",
    ] {
        assert!(after_top.contains(field), "section missing {field}: {after_top}");
    }
    // And the body verbatim.
    assert!(after_top.contains("Body paragraph one."));
    assert!(after_top.contains("Body paragraph two."));

    // The literal `\n---\n` separator must appear between top-level and section.
    assert!(bundle.contains("\n---\n\n---\n"), "missing \\n---\\n separator into section: {bundle}");
}
