//! Acceptance test for AC8 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: `--include-recall-stats` adds two extra frontmatter fields per memory: `mattered: "low|medium|high"` derived from recall_count quantiles within the bundle, and `dormancy_days: <N>` = days between created_at and last_recalled_at (or 0).
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::too_many_lines)]

mod common;
use common::{FakeMemory, stage_recall_root};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac8() {
    let tmp = TempDir::new().unwrap();
    // Six memories with recall_counts 0,1,2,3,4,100 to force a clear
    // tertile split. The 100-count must land in "high"; the 0-count in "low".
    // dormancy: pick distinct last_recalled_at values so we can verify a
    // specific count.
    let mems = [
        FakeMemory {
            id: "01KS00000000000000000LOW0001",
            kind: "semantic",
            subject: "user",
            created_at: "2026-01-01T00:00:00Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "LOW1\n",
        },
        FakeMemory {
            id: "01KS00000000000000000LOW0002",
            kind: "semantic",
            subject: "user",
            created_at: "2026-01-02T00:00:00Z",
            recall_count: 1,
            last_recalled_at: None,
            private: false,
            body: "LOW2\n",
        },
        FakeMemory {
            id: "01KS00000000000000000MED0001",
            kind: "semantic",
            subject: "user",
            created_at: "2026-02-01T00:00:00Z",
            recall_count: 2,
            last_recalled_at: None,
            private: false,
            body: "MED1\n",
        },
        FakeMemory {
            id: "01KS00000000000000000MED0002",
            kind: "semantic",
            subject: "user",
            created_at: "2026-02-02T00:00:00Z",
            recall_count: 3,
            last_recalled_at: None,
            private: false,
            body: "MED2\n",
        },
        FakeMemory {
            id: "01KS00000000000000000HIGH001",
            kind: "semantic",
            subject: "user",
            created_at: "2026-03-01T00:00:00Z",
            recall_count: 4,
            last_recalled_at: None,
            private: false,
            body: "HIGH1\n",
        },
        FakeMemory {
            id: "01KS00000000000000000HIGH002",
            kind: "semantic",
            subject: "user",
            // Created Jan 1, last recalled Jan 11 -> dormancy 10.
            created_at: "2026-01-01T00:00:00Z",
            recall_count: 100,
            last_recalled_at: Some("2026-01-11T00:00:00Z"),
            private: false,
            body: "HIGH2\n",
        },
    ];
    let (root, recall_cmd) = stage_recall_root(tmp.path(), &mems);
    let bin = env!("CARGO_BIN_EXE_reliquary");

    let out = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026", "--include-recall-stats"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&recall_cmd)
        .output()
        .unwrap();
    assert!(out.status.success(), "stderr={}", String::from_utf8_lossy(&out.stderr));
    let bundle = String::from_utf8(out.stdout).unwrap();

    // mattered field must appear at least once for each tier.
    assert!(bundle.contains("mattered: \"low\""), "no low tier: {bundle}");
    assert!(bundle.contains("mattered: \"medium\""), "no medium tier: {bundle}");
    assert!(bundle.contains("mattered: \"high\""), "no high tier: {bundle}");
    // dormancy_days field appears in every section.
    assert!(bundle.contains("dormancy_days:"), "no dormancy_days field: {bundle}");
    // The HIGH002 memory specifically must show dormancy 10.
    let idx = bundle.find("HIGH002").expect("HIGH002 id missing");
    let section_tail = &bundle[idx..];
    let close = section_tail.find("---").expect("section close missing");
    let section = &section_tail[..close];
    assert!(section.contains("dormancy_days: 10"),
        "expected dormancy_days: 10 in HIGH002 section, got: {section}");
}
