//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: When the recall-root path does not exist or is not a directory: exit 2 with stderr containing the path and `recall root not found`.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac5() {
    let tmp = TempDir::new().unwrap();
    let bogus = tmp.path().join("does-not-exist-anywhere");
    let bin = env!("CARGO_BIN_EXE_reliquary");

    let out = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026"])
        .arg("--recall-root").arg(&bogus)
        .output()
        .unwrap();

    assert_eq!(out.status.code(), Some(2), "expected exit 2, got {:?}; stderr={}",
        out.status.code(), String::from_utf8_lossy(&out.stderr));
    let stderr = String::from_utf8(out.stderr).unwrap();
    assert!(stderr.contains("recall root not found"), "stderr missing canonical phrase: {stderr}");
    assert!(stderr.contains(bogus.to_str().unwrap()), "stderr missing path: {stderr}");
}
