//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: `reliquary compose --year <YYYY> [--recall-root <dir>] [--out <file>]` reads memory index entries with subject==user and created_at within the calendar year, slurps each memory's Markdown body from disk, and emits a single bundle file. Default --recall-root: `$RECALL_HOME` or `~/.claude/recall`. Default --out: stdout.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

mod common;
use common::{FakeMemory, stage_recall_root};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac1() {
    let tmp = TempDir::new().unwrap();
    let mems = [
        FakeMemory {
            id: "01KS00000000000000000IN0001",
            kind: "semantic",
            subject: "user",
            created_at: "2026-03-15T10:00:00Z",
            recall_count: 2,
            last_recalled_at: Some("2026-04-01T12:00:00Z"),
            private: false,
            body: "Apples taste like autumn.\n",
        },
        // A memory in a different year — must be excluded.
        FakeMemory {
            id: "01KS00000000000000000OUT001",
            kind: "semantic",
            subject: "user",
            created_at: "2025-12-31T23:00:00Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "Old memory.\n",
        },
    ];
    let (root, recall_cmd) = stage_recall_root(tmp.path(), &mems);
    let out_path = tmp.path().join("bundle.md");

    let bin = env!("CARGO_BIN_EXE_reliquary");
    let status = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&recall_cmd)
        .arg("--out").arg(&out_path)
        .output()
        .unwrap();
    assert!(
        status.status.success(),
        "compose failed: stdout={} stderr={}",
        String::from_utf8_lossy(&status.stdout),
        String::from_utf8_lossy(&status.stderr),
    );

    let bundle = std::fs::read_to_string(&out_path).unwrap();
    assert!(bundle.contains("Apples taste like autumn"), "in-year body missing: {bundle}");
    assert!(!bundle.contains("Old memory"), "out-of-year body leaked: {bundle}");
    assert!(bundle.contains("year: 2026"), "top frontmatter year missing: {bundle}");
}
