//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: `--subject <prefix>` overrides the default `user` subject filter (useful for `--subject self` to generate the agent's-own-memories companion volume).
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

mod common;
use common::{FakeMemory, stage_recall_root};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac7() {
    let tmp = TempDir::new().unwrap();
    let mems = [
        FakeMemory {
            id: "01KS00000000000000000USER001",
            kind: "semantic",
            subject: "user",
            created_at: "2026-08-08T08:08:08Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "User body.\n",
        },
        FakeMemory {
            id: "01KS00000000000000000SELF001",
            kind: "semantic",
            subject: "self",
            created_at: "2026-08-09T08:08:08Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "Self body.\n",
        },
    ];
    let (root, recall_cmd) = stage_recall_root(tmp.path(), &mems);
    let bin = env!("CARGO_BIN_EXE_reliquary");

    let out_self = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026", "--subject", "self"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&recall_cmd)
        .output()
        .unwrap();
    assert!(out_self.status.success(), "stderr={}", String::from_utf8_lossy(&out_self.stderr));
    let bundle_self = String::from_utf8(out_self.stdout).unwrap();
    assert!(bundle_self.contains("Self body"), "self body missing: {bundle_self}");
    assert!(!bundle_self.contains("User body"), "user body leaked into self bundle: {bundle_self}");

    // Default subject (user) is the inverse check.
    let out_user = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&recall_cmd)
        .output()
        .unwrap();
    assert!(out_user.status.success(), "stderr={}", String::from_utf8_lossy(&out_user.stderr));
    let bundle_user = String::from_utf8(out_user.stdout).unwrap();
    assert!(bundle_user.contains("User body"), "user body missing in default subject: {bundle_user}");
    assert!(!bundle_user.contains("Self body"), "self body leaked into user bundle: {bundle_user}");
}
