//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: Memories whose frontmatter contains `private: true` are excluded from the bundle. The top-level frontmatter records `excluded_private_count: <N>` so the omission is auditable.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

mod common;
use common::{FakeMemory, stage_recall_root};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac4() {
    let tmp = TempDir::new().unwrap();
    let mems = [
        FakeMemory {
            id: "01KS00000000000000000PUBLIC1",
            kind: "semantic",
            subject: "user",
            created_at: "2026-04-04T04:04:04Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "PUBLIC body — should appear.\n",
        },
        FakeMemory {
            id: "01KS00000000000000000SECRET1",
            kind: "semantic",
            subject: "user",
            created_at: "2026-04-04T04:04:05Z",
            recall_count: 0,
            last_recalled_at: None,
            private: true,
            body: "SECRET body — must NOT appear.\n",
        },
        FakeMemory {
            id: "01KS00000000000000000SECRET2",
            kind: "semantic",
            subject: "user",
            created_at: "2026-04-04T04:04:06Z",
            recall_count: 0,
            last_recalled_at: None,
            private: true,
            body: "ANOTHER SECRET — must NOT appear.\n",
        },
    ];
    let (root, recall_cmd) = stage_recall_root(tmp.path(), &mems);

    let bin = env!("CARGO_BIN_EXE_reliquary");
    let out = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&recall_cmd)
        .output()
        .unwrap();
    assert!(out.status.success(), "stderr={}", String::from_utf8_lossy(&out.stderr));
    let bundle = String::from_utf8(out.stdout).unwrap();

    assert!(bundle.contains("PUBLIC body"), "public body missing: {bundle}");
    assert!(!bundle.contains("SECRET body"), "secret body leaked: {bundle}");
    assert!(!bundle.contains("ANOTHER SECRET"), "second secret leaked: {bundle}");
    assert!(!bundle.contains("01KS00000000000000000SECRET1"), "secret id leaked");
    assert!(!bundle.contains("01KS00000000000000000SECRET2"), "secret id leaked");
    assert!(bundle.contains("excluded_private_count: 2"), "audit count missing: {bundle}");
}
