//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: A memory file whose YAML frontmatter is unparseable is skipped (not crashed) and a warning line is written to stderr: `WARN: skipping <path>: frontmatter parse error: <msg>`. The bundle continues.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

mod common;
use common::{FakeMemory, stage_recall_root, write_raw_memory};
use serde_json::json;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac6() {
    let tmp = TempDir::new().unwrap();
    let good = [FakeMemory {
        id: "01KS00000000000000000GOOD001",
        kind: "semantic",
        subject: "user",
        created_at: "2026-07-07T07:07:07Z",
        recall_count: 0,
        last_recalled_at: None,
        private: false,
        body: "Good body — survives.\n",
    }];
    let (root, _recall_cmd) = stage_recall_root(tmp.path(), &good);

    // Inject a malformed memory file (broken YAML).
    let bad_path = write_raw_memory(
        tmp.path(),
        "user",
        "01KS00000000000000000BAD0001",
        "---\nthis is : not : valid : yaml\n  : indent: broken\nfoo bar baz\n",
    );

    // Custom recall stub that lists BOTH memories so the binary attempts
    // to read the malformed one.
    let json_arr = json!([
        {
            "id": "01KS00000000000000000GOOD001",
            "kind": "semantic",
            "subject": "user",
            "path": root.join("memories").join("user").join("01KS00000000000000000GOOD001.md").to_string_lossy(),
            "recall_count": 0,
            "last_recalled_at": null,
            "confidence": 0.5,
        },
        {
            "id": "01KS00000000000000000BAD0001",
            "kind": "semantic",
            "subject": "user",
            "path": bad_path.to_string_lossy(),
            "recall_count": 0,
            "last_recalled_at": null,
            "confidence": 0.5,
        }
    ]);
    let json_path = tmp.path().join("recall-ac6.json");
    fs::write(&json_path, serde_json::to_string(&json_arr).unwrap()).unwrap();
    let script = tmp.path().join("recall_ac6.sh");
    fs::write(&script, format!("#!/bin/sh\ncat {}\n", json_path.display())).unwrap();
    let mut perms = fs::metadata(&script).unwrap().permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&script, perms).unwrap();

    let bin = env!("CARGO_BIN_EXE_reliquary");
    let out = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&script)
        .output()
        .unwrap();

    assert!(out.status.success(), "should not crash; stderr={}", String::from_utf8_lossy(&out.stderr));

    let bundle = String::from_utf8(out.stdout).unwrap();
    let stderr = String::from_utf8(out.stderr).unwrap();

    assert!(bundle.contains("Good body"), "good memory was dropped: {bundle}");
    assert!(stderr.contains("WARN: skipping"), "missing WARN line: {stderr}");
    assert!(stderr.contains("frontmatter parse error"), "missing parse-error phrase: {stderr}");
    assert!(stderr.contains(bad_path.to_str().unwrap()), "WARN missing path: {stderr}");
}
