//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: memory-reliquary (cli)
//! AC description: Memories are ordered by created_at ascending. Two memories with identical timestamps tiebreak by id.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

mod common;
use common::{FakeMemory, stage_recall_root};
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac3() {
    let tmp = TempDir::new().unwrap();
    // Three memories: two share a timestamp, one is later. Provide them in
    // a scrambled order so we know the sorter ran.
    let mems = [
        FakeMemory {
            id: "01KS00000000000000000ZULU03",
            kind: "semantic",
            subject: "user",
            created_at: "2026-06-01T00:00:00Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "C body\n",
        },
        FakeMemory {
            id: "01KS00000000000000000BETA02",
            kind: "semantic",
            subject: "user",
            created_at: "2026-01-01T00:00:00Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "B body\n",
        },
        FakeMemory {
            id: "01KS00000000000000000ALPHA1",
            kind: "semantic",
            subject: "user",
            created_at: "2026-01-01T00:00:00Z",
            recall_count: 0,
            last_recalled_at: None,
            private: false,
            body: "A body\n",
        },
    ];
    let (root, recall_cmd) = stage_recall_root(tmp.path(), &mems);

    let bin = env!("CARGO_BIN_EXE_reliquary");
    let out = Command::new(bin)
        .arg("compose")
        .args(["--year", "2026"])
        .arg("--recall-root").arg(&root)
        .arg("--recall-cmd").arg(&recall_cmd)
        .output()
        .unwrap();
    assert!(out.status.success(), "stderr={}", String::from_utf8_lossy(&out.stderr));
    let bundle = String::from_utf8(out.stdout).unwrap();

    let pos_alpha = bundle.find("ALPHA1").expect("ALPHA1 not found");
    let pos_beta = bundle.find("BETA02").expect("BETA02 not found");
    let pos_zulu = bundle.find("ZULU03").expect("ZULU03 not found");

    assert!(pos_alpha < pos_beta, "id tiebreak: ALPHA must precede BETA at same ts");
    assert!(pos_beta < pos_zulu, "chronological: BETA (Jan) must precede ZULU (Jun)");
}
