//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: conversations-zine (cli)
//! AC description: `--format text` prints each moment as: a horizontal rule, the session_id/turn_index/timestamp/score header, blockquoted user_text, blank line, assistant_text, blank line, `(why: <reason>)` italicised. Easy to skim in less.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac7() {
    let root = TempDir::new().unwrap();
    let recs = [
        serde_json::json!({
            "type": "user",
            "message": {"role": "user", "content": "ping question"},
            "timestamp": "2026-05-01T00:00:00Z",
        }),
        serde_json::json!({
            "type": "assistant",
            "message": {"role": "assistant", "content": [{"type":"text","text":"pong reply"}]},
            "timestamp": "2026-05-01T00:00:01Z",
        }),
    ];
    let mut s = String::new();
    for r in &recs {
        s.push_str(&serde_json::to_string(r).unwrap());
        s.push('\n');
    }
    std::fs::write(root.path().join("t.jsonl"), s).unwrap();

    let bin = env!("CARGO_BIN_EXE_zine");
    let out = Command::new(bin)
        .args(["extract", "--since", "90d", "--root"])
        .arg(root.path())
        .args(["--limit", "5", "--format", "text"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let text = String::from_utf8(out.stdout).unwrap();

    // Horizontal rule (a run of dashes).
    assert!(text.contains("----"), "expected horizontal rule of dashes");
    // Header with session_id, turn_index, timestamp, score.
    assert!(text.contains("t"), "expected session id in header");
    assert!(text.contains("turn 0"), "expected turn index in header");
    assert!(text.contains("2026-05-01T00:00:00Z"), "expected timestamp");
    assert!(text.contains("score "), "expected score label");
    // Blockquoted user text: a line starting with "> ".
    assert!(
        text.lines().any(|l| l.starts_with("> ")),
        "expected blockquoted user_text"
    );
    // Assistant text appears.
    assert!(text.contains("pong reply"), "expected assistant text body");
    // why line italicised with markdown asterisks and prefix "(why:".
    assert!(
        text.contains("*(why: "),
        "expected italicised (why: ...) line; got:\n{text}"
    );
}
