//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Exit code reflects findings: 0 = no findings, 1 = at least one finding, 2 = invocation error (bad path, unreadable file, malformed args). Exit codes are stable across runs on identical inputs.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac7() {
    let bin = env!("CARGO_BIN_EXE_recall-lint");

    // 0: empty corpus.
    let empty = TempDir::new().unwrap();
    let out = Command::new(bin).arg(empty.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));

    // 1: corpus with at least one finding (duplicate pair).
    let dup_root = TempDir::new().unwrap();
    fs::write(dup_root.path().join("a.md"), "---\n---\nx\n").unwrap();
    fs::write(dup_root.path().join("b.md"), "---\n---\nx\n").unwrap();
    let out = Command::new(bin)
        .arg(dup_root.path())
        .args(["--stale-days", "36500"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));

    // 2: bad path.
    let out = Command::new(bin).arg("/no/such/path/here").output().unwrap();
    assert_eq!(out.status.code(), Some(2));
}
