//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Detects broken `[[wiki-links]]`: a link `[[target]]` resolves if any *.md file under the root has stem `target` or relative path `target.md`; otherwise emits finding kind=`broken_link` with source path, target, and 1-indexed line number.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac5() {
    let root = TempDir::new().unwrap();
    // index.md has 2 wiki-links: one resolves, one is broken.
    fs::write(
        root.path().join("index.md"),
        "---\n---\nfirst line\nsee [[exists]] and [[missing]] in this list\n",
    )
    .unwrap();
    fs::write(root.path().join("exists.md"), "---\n---\nI exist\n").unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-lint");
    let out = Command::new(bin)
        .arg(root.path())
        .args(["--format", "json", "--stale-days", "36500"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_str(&String::from_utf8(out.stdout).unwrap()).unwrap();
    let broken: Vec<&serde_json::Value> = json["findings"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|f| f["kind"] == "broken_link")
        .collect();
    assert_eq!(broken.len(), 1, "exactly 1 broken link: {:?}", json["findings"]);
    let entry = broken[0];
    assert_eq!(entry["target"], "missing");
    assert_eq!(entry["line"], 2, "1-indexed line number (body line 2): {entry:?}");
    let path = entry["path"].as_str().unwrap();
    assert!(path.ends_with("index.md"));
}
