//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: CLI binary `recall-lint` accepts a positional path to a memory root directory and exits 0 when the directory is empty, emitting an empty findings array in JSON mode.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac1() {
    let dir = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-lint");
    let out = Command::new(bin)
        .arg(dir.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert!(json["findings"].as_array().unwrap().is_empty());
}
