//! Acceptance test for AC9 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Frontmatter is optional; entries without frontmatter use file mtime as the freshness signal and are never flagged as `stale` solely because frontmatter is absent.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac9() {
    let root = TempDir::new().unwrap();
    // No frontmatter at all — should be considered fresh via mtime.
    fs::write(root.path().join("plain.md"), "Just body text, no frontmatter fence.\n").unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-lint");
    let out = Command::new(bin)
        .arg(root.path())
        .args(["--format", "json", "--stale-days", "30"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_str(&String::from_utf8(out.stdout).unwrap()).unwrap();
    let findings = json["findings"].as_array().unwrap();
    let stale: Vec<&serde_json::Value> = findings.iter().filter(|f| f["kind"] == "stale").collect();
    assert!(stale.is_empty(), "frontmatter-less file freshly created must not be stale: {findings:?}");
}
