//! Acceptance test for AC10 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Supports `--ignore <glob>` (repeatable) to skip paths matching the glob; ignored files contribute neither to duplicate detection nor to wiki-link resolution.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac10() {
    let root = TempDir::new().unwrap();
    fs::write(root.path().join("kept.md"), "---\n---\nthe body\n").unwrap();
    fs::write(root.path().join("dropme.md"), "---\n---\nthe body\n").unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-lint");

    // Without --ignore: duplicate detected.
    let out = Command::new(bin)
        .arg(root.path())
        .args(["--format", "json", "--stale-days", "36500"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_str(&String::from_utf8(out.stdout).unwrap()).unwrap();
    let dups: Vec<&serde_json::Value> = json["findings"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|f| f["kind"] == "duplicate")
        .collect();
    assert_eq!(dups.len(), 1, "without --ignore, duplicate present");

    // With --ignore 'dropme.md': no duplicate.
    let out = Command::new(bin)
        .arg(root.path())
        .args(["--format", "json", "--stale-days", "36500", "--ignore", "dropme.md"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_str(&String::from_utf8(out.stdout).unwrap()).unwrap();
    let dups: Vec<&serde_json::Value> = json["findings"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|f| f["kind"] == "duplicate")
        .collect();
    assert!(dups.is_empty(), "with --ignore, duplicate must NOT be reported");
}
