//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Computes missing: `memories_meta` rows whose `path` column points to a non-existent file. Reports `missing: [<id>...]` sorted lexicographically.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac5() {
    let root = TempDir::new().unwrap();
    // Index references 01XXX whose path does not exist on disk.
    let idx = root.path().join("index");
    fs::create_dir_all(&idx).unwrap();
    let db = idx.join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, embedding_id TEXT);
INSERT INTO memories_meta VALUES ('01XXX','semantic','user','/tmp/totally-missing-file.md',NULL);";
    let _ = Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-doctor");
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let missing: Vec<&str> = json["missing"].as_array().unwrap().iter().map(|v| v.as_str().unwrap()).collect();
    assert!(missing.contains(&"01XXX"), "expected 01XXX in missing: {json}");
}
