//! Acceptance test for AC9 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: `--fix` invokes `recall reindex` (shelling out via PATH) when orphans OR missing is non-empty. Default (no --fix) is read-only — never writes. When `recall` isn't on PATH, `--fix` emits a warning and exits with code 1.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac9() {
    let bin = env!("CARGO_BIN_EXE_recall-doctor");
    let root = TempDir::new().unwrap();
    let mem = root.path().join("memories").join("user");
    fs::create_dir_all(&mem).unwrap();
    fs::write(
        mem.join("01A.md"),
        "---\nid: 01A\nkind: semantic\nsubject: user\n---\nbody\n",
    )
    .unwrap();
    // No index DB → diverged → --fix tries `recall reindex` → recall almost certainly
    // not on PATH in CI → exit 1 with warning. Locally if recall IS on PATH, it would
    // try to reindex; either way, no panic. Just assert NO panic and a sensible exit.
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .arg("--fix")
        // Use an env scoped PATH that excludes the user's bins so recall is unreachable.
        .env("PATH", "/usr/bin:/bin")
        .output()
        .unwrap();
    let code = out.status.code();
    assert!(
        matches!(code, Some(0) | Some(1)),
        "exit should be 0 or 1, was {:?}",
        code
    );
}
