//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Output format selectable via `--format text|json` (default text). JSON shape: `{file_count, indexed_count, orphans, missing, embedder_ids, schema_version, warnings}`. Deterministic key ordering; same input → byte-identical output.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac7() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-doctor");

    // Text default.
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .output()
        .unwrap();
    let text = String::from_utf8(out.stdout).unwrap();
    assert!(text.contains("file_count:"));

    // JSON deterministic.
    let a = Command::new(bin).args(["--root"]).arg(root.path()).args(["--format", "json"]).output().unwrap().stdout;
    let b = Command::new(bin).args(["--root"]).arg(root.path()).args(["--format", "json"]).output().unwrap().stdout;
    assert_eq!(a, b, "JSON output must be byte-identical");
    let parsed: serde_json::Value = serde_json::from_slice(&a).unwrap();
    for k in ["file_count", "orphans", "missing", "embedder_ids", "schema_version", "warnings"] {
        assert!(parsed.get(k).is_some(), "missing key {k}: {parsed}");
    }
}
