//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Exit code 0 when in sync (orphans+missing empty AND indexed_count == file_count). Exit code 1 when divergent. Exit code 2 on invocation error (bad --root that exists but isn't a dir, malformed args). Stable across runs.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac8() {
    let bin = env!("CARGO_BIN_EXE_recall-doctor");

    // 0: Nonexistent root counts as in-sync trivially (file_count=0, no DB).
    // Per AC: orphans+missing empty AND indexed_count == file_count. With no DB indexed_count=null,
    // so this is NOT clean. Use a populated in-sync fixture instead.
    let in_sync = TempDir::new().unwrap();
    let mem = in_sync.path().join("memories").join("user");
    fs::create_dir_all(&mem).unwrap();
    fs::write(
        mem.join("01A.md"),
        "---\nid: 01A\nkind: semantic\nsubject: user\n---\nbody\n",
    )
    .unwrap();
    let idx = in_sync.path().join("index");
    fs::create_dir_all(&idx).unwrap();
    let db = idx.join("recall.sqlite");
    let sql = format!(
        "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, embedding_id TEXT);
INSERT INTO memories_meta VALUES ('01A','semantic','user','{}',NULL);",
        mem.join("01A.md").display()
    );
    let _ = Command::new("sqlite3").arg(&db).arg(&sql).output().unwrap();
    let out = Command::new(bin)
        .args(["--root"])
        .arg(in_sync.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0), "expected exit 0 for in-sync fixture");

    // 1: divergent (file on disk not in index).
    fs::write(
        mem.join("01B.md"),
        "---\nid: 01B\nkind: semantic\nsubject: user\n---\nbody\n",
    )
    .unwrap();
    let out = Command::new(bin)
        .args(["--root"])
        .arg(in_sync.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));

    // 2: --root that's a file, not a dir.
    let not_a_dir = NamedTempFile::new().unwrap();
    let out = Command::new(bin)
        .args(["--root"])
        .arg(not_a_dir.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
}
