//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Walks `<root>/memories/` recursively, counting *.md files; ignores non-Markdown and dot-prefixed directories. Reports `file_count: N`.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

fn write_memory(root: &std::path::Path, sub: &str, id: &str) {
    let dir = root.join("memories").join(sub);
    fs::create_dir_all(&dir).unwrap();
    fs::write(
        dir.join(format!("{id}.md")),
        format!("---\nid: {id}\nkind: semantic\nsubject: {sub}\n---\nbody\n"),
    )
    .unwrap();
}

#[test]
fn acceptance_ac2() {
    let root = TempDir::new().unwrap();
    write_memory(root.path(), "user", "01A");
    write_memory(root.path(), "self", "01B");
    fs::write(root.path().join("memories").join("notes.txt"), "ignore me").unwrap();
    fs::create_dir_all(root.path().join("memories").join(".hidden")).unwrap();
    fs::write(
        root.path().join("memories").join(".hidden").join("c.md"),
        "---\nid: 01C\n---\nshould skip\n",
    )
    .unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-doctor");
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["file_count"], 2, "expected 2; .hidden + .txt excluded: {json}");
}
