//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Reports `embedder_ids: [<id>...]` — distinct `embedding_id` values from `memories_meta` (excluding NULL). Empty list when no rows or no embeddings.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac6() {
    let root = TempDir::new().unwrap();
    let idx = root.path().join("index");
    fs::create_dir_all(&idx).unwrap();
    let db = idx.join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, embedding_id TEXT);
INSERT INTO memories_meta VALUES ('01A','s','u','/x','hash-v1');
INSERT INTO memories_meta VALUES ('01B','s','u','/y','bge-small-v1.5');
INSERT INTO memories_meta VALUES ('01C','s','u','/z',NULL);";
    let _ = Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-doctor");
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let ids: Vec<&str> = json["embedder_ids"].as_array().unwrap().iter().map(|v| v.as_str().unwrap()).collect();
    assert!(ids.contains(&"hash-v1"));
    assert!(ids.contains(&"bge-small-v1.5"));
    // NULL should be excluded (no empty string).
    assert!(!ids.contains(&""));
}
