//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Queries `<root>/index/recall.sqlite` `memories_meta` table for row count; reports `indexed_count: N`. Missing DB → `indexed_count: null` and warning. Shells out to `sqlite3` binary; absence of `sqlite3` → reports `indexed_count: null` + warning.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac3() {
    let root = TempDir::new().unwrap();
    // No DB present: indexed_count should be absent/null + a warning.
    let bin = env!("CARGO_BIN_EXE_recall-doctor");
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert!(json["indexed_count"].is_null() || json.get("indexed_count").is_none());
    let warnings = json["warnings"].as_array().unwrap();
    assert!(warnings.iter().any(|w| w.as_str().unwrap_or("").contains("not found")));
}
