//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Reports `schema_version: <string>` derived from a `meta` table or `PRAGMA user_version`; falls back to `"v0.1-undeclared"` when no schema version is queryable. Documented in the report so /self-review can warn on bumps.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac10() {
    let bin = env!("CARGO_BIN_EXE_recall-doctor");

    // No DB → fallback string.
    let root = TempDir::new().unwrap();
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["schema_version"], "v0.1-undeclared");

    // DB with PRAGMA user_version=2 → user_version=2.
    let with_db = TempDir::new().unwrap();
    let idx = with_db.path().join("index");
    fs::create_dir_all(&idx).unwrap();
    let db = idx.join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, embedding_id TEXT);
PRAGMA user_version = 2;";
    let _ = Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();
    let out = Command::new(bin)
        .args(["--root"])
        .arg(with_db.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["schema_version"], "user_version=2");
}
