//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: Computes orphans: file IDs present on disk (parsed from frontmatter `id:` field) but not in `memories_meta`. Reports `orphans: [<id>...]` sorted lexicographically.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

fn build_fixture(root: &std::path::Path) {
    let mem = root.join("memories").join("user");
    fs::create_dir_all(&mem).unwrap();
    for id in ["01AAA", "01BBB"] {
        fs::write(
            mem.join(format!("{id}.md")),
            format!("---\nid: {id}\nkind: semantic\nsubject: user\n---\nbody\n"),
        )
        .unwrap();
    }
    // Build an index DB with only 01AAA — 01BBB is orphaned on disk.
    let idx = root.join("index");
    fs::create_dir_all(&idx).unwrap();
    let db = idx.join("recall.sqlite");
    let path_str = mem.join("01AAA.md").to_string_lossy().to_string();
    let sql = format!(
        "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, embedding_id TEXT);
INSERT INTO memories_meta VALUES ('01AAA','semantic','user','{path_str}',NULL);",
    );
    let _ = Command::new("sqlite3").arg(&db).arg(&sql).output().unwrap();
}

#[test]
fn acceptance_ac4() {
    let root = TempDir::new().unwrap();
    build_fixture(root.path());

    let bin = env!("CARGO_BIN_EXE_recall-doctor");
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let orphans: Vec<&str> = json["orphans"].as_array().unwrap().iter().map(|v| v.as_str().unwrap()).collect();
    assert_eq!(orphans, vec!["01BBB"]);
}
