//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-doctor (cli)
//! AC description: CLI binary `recall-doctor` accepts `[--root <dir>]` (default `~/.claude/recall`). Reads the directory, prints a divergence report to stdout, exits 0 when in sync. Empty/nonexistent root → exit 0 with empty report.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac1() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-doctor");
    let out = Command::new(bin)
        .args(["--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["file_count"], 0);
}
