//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Tensor names from safetensors that contain `.` or `/` are sanitized to uppercase Rust-identifier-safe names (`weight.ih` → `WEIGHT_IH`, `layer/0/weight` → `LAYER_0_WEIGHT`). Conflicts after sanitization → exit 4 with stderr listing the colliding names.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

use safetensors::{Dtype, View, serialize_to_file};
use tempfile::TempDir;

struct Tensor {
    dtype: Dtype,
    shape: Vec<usize>,
    data: Vec<u8>,
}

impl View for &Tensor {
    fn dtype(&self) -> Dtype { self.dtype }
    fn shape(&self) -> &[usize] { &self.shape }
    fn data(&self) -> std::borrow::Cow<'_, [u8]> { std::borrow::Cow::Borrowed(&self.data) }
    fn data_len(&self) -> usize { self.data.len() }
}

fn f32_tensor(shape: Vec<usize>, values: &[f32]) -> Tensor {
    let mut data = Vec::with_capacity(values.len() * 4);
    for v in values {
        data.extend_from_slice(&v.to_le_bytes());
    }
    Tensor { dtype: Dtype::F32, shape, data }
}

#[test]
fn ac4_sanitization_succeeds() {
    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("clean.safetensors");
    let out_path = dir.path().join("clean.rs");

    let tensors: Vec<(String, Tensor)> = vec![
        ("weight.ih".to_string(), f32_tensor(vec![2], &[1.0, 2.0])),
        ("layer/0/weight".to_string(), f32_tensor(vec![2], &[3.0, 4.0])),
        ("bn1.running_mean".to_string(), f32_tensor(vec![2], &[5.0, 6.0])),
    ];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let out = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "x",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(out.status.success(), "stderr={}", String::from_utf8_lossy(&out.stderr));
    let src = std::fs::read_to_string(&out_path).unwrap();
    assert!(src.contains("pub const WEIGHT_IH:"), "{src}");
    assert!(src.contains("pub const LAYER_0_WEIGHT:"), "{src}");
    assert!(src.contains("pub const BN1_RUNNING_MEAN:"), "{src}");
}

#[test]
fn acceptance_ac4() {
    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("collide.safetensors");
    let out_path = dir.path().join("collide.rs");

    // "weight.ih" and "weight/ih" both sanitize to WEIGHT_IH.
    let tensors: Vec<(String, Tensor)> = vec![
        ("weight.ih".to_string(), f32_tensor(vec![2], &[1.0, 2.0])),
        ("weight/ih".to_string(), f32_tensor(vec![2], &[3.0, 4.0])),
    ];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let out = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "x",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();

    assert_eq!(
        out.status.code(),
        Some(4),
        "expected exit 4 for collision, got {:?}, stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("weight.ih"), "stderr missing collider 'weight.ih':\n{stderr}");
    assert!(stderr.contains("weight/ih"), "stderr missing collider 'weight/ih':\n{stderr}");
    assert!(!out_path.exists(), "collision must not leave a partial output file");
}
