//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Const arrays preserve f32 precision exactly — round-tripping (write tensor → safetensors → bake → const → parse from emitted source) yields bit-identical f32 bytes. Use Rust's `{:e}` or `f32::from_bits` style if needed to avoid lossy formatting.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::cast_precision_loss,
    clippy::as_conversions,
    clippy::excessive_precision,
    clippy::panic,
)]

use std::process::Command;

use safetensors::{Dtype, View, serialize_to_file};
use tempfile::TempDir;

struct Tensor {
    dtype: Dtype,
    shape: Vec<usize>,
    data: Vec<u8>,
}

impl View for &Tensor {
    fn dtype(&self) -> Dtype { self.dtype }
    fn shape(&self) -> &[usize] { &self.shape }
    fn data(&self) -> std::borrow::Cow<'_, [u8]> { std::borrow::Cow::Borrowed(&self.data) }
    fn data_len(&self) -> usize { self.data.len() }
}

fn f32_tensor(shape: Vec<usize>, values: &[f32]) -> Tensor {
    let mut data = Vec::with_capacity(values.len() * 4);
    for v in values {
        data.extend_from_slice(&v.to_le_bytes());
    }
    Tensor { dtype: Dtype::F32, shape, data }
}

/// Extract all decimal/special f32 literals from a single `pub const`
/// line such as `pub const X: [f32; 3] = [1.0e0_f32, 2.5e0_f32, ...];`.
/// We strip the `_f32` suffix so `.parse::<f32>()` succeeds.
fn collect_literals(src: &str, ident: &str) -> Vec<f32> {
    let needle = format!("pub const {ident}:");
    let line = src
        .lines()
        .find(|l| l.starts_with(&needle))
        .unwrap_or_else(|| panic!("no line for {ident}:\n{src}"));
    let rhs = line.split_once('=').unwrap().1.trim().trim_end_matches(';');
    let mut out = Vec::new();
    // Tokenize: numbers + special-literal idents.
    let mut buf = String::new();
    for ch in rhs.chars() {
        if ch.is_ascii_alphanumeric() || ch == '.' || ch == '+' || ch == '-' || ch == '_' || ch == ':' {
            buf.push(ch);
        } else if !buf.is_empty() {
            push_literal(&mut out, &buf);
            buf.clear();
        }
    }
    if !buf.is_empty() {
        push_literal(&mut out, &buf);
    }
    out
}

fn push_literal(out: &mut Vec<f32>, tok: &str) {
    let t = tok.trim_end_matches("_f32");
    if t == "f32::NAN" {
        out.push(f32::NAN);
        return;
    }
    if t == "f32::INFINITY" {
        out.push(f32::INFINITY);
        return;
    }
    if t == "f32::NEG_INFINITY" {
        out.push(f32::NEG_INFINITY);
        return;
    }
    if let Ok(v) = t.parse::<f32>() {
        out.push(v);
    }
}

#[test]
fn acceptance_ac2() {
    // Adversarial f32 set: cover denormals, near-1.0 mantissa-dense
    // values, e^... values, tiny values, large values, pi-ish.
    let tricky: Vec<f32> = vec![
        0.0,
        -0.0,
        1.0,
        -1.0,
        f32::MIN_POSITIVE,
        f32::from_bits(1),                  // smallest denormal
        f32::from_bits(0x7f7f_ffff),        // f32::MAX
        f32::from_bits(0x3f80_0001),        // 1.0 + 1 ulp
        std::f32::consts::PI,
        std::f32::consts::E,
        1.234_567_8e-20,
        -9.876_543e+20,
    ];

    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("rt.safetensors");
    let out_path = dir.path().join("rt.rs");

    let tensors: Vec<(String, Tensor)> = vec![("vals".to_string(), f32_tensor(vec![tricky.len()], &tricky))];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let out = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "rt",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(out.status.success(), "stderr={}", String::from_utf8_lossy(&out.stderr));

    let src = std::fs::read_to_string(&out_path).unwrap();
    let parsed = collect_literals(&src, "VALS");
    assert_eq!(parsed.len(), tricky.len(), "literal count mismatch\n{src}");

    for (i, (orig, got)) in tricky.iter().zip(parsed.iter()).enumerate() {
        // NaN: bits are not unique, but is_nan() must hold.
        if orig.is_nan() {
            assert!(got.is_nan(), "idx {i}: expected NaN, got {got}");
            continue;
        }
        assert_eq!(
            orig.to_bits(),
            got.to_bits(),
            "idx {i}: orig={orig:?} ({:#010x}) got={got:?} ({:#010x})",
            orig.to_bits(),
            got.to_bits()
        );
    }
}
