//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: `morsel-bake --in <safetensors-file> --arch <name> --out <rust-file>` reads tensors from the safetensors file, emits Rust source containing one `pub const NAME: [[f32; N]; M] = ...;` (or 1-D `[f32; N]`) per tensor, plus `pub const ARCH_FINGERPRINT: &str = "<arch>-<dim-summary>-v1";`. Exit 0 on success.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::cast_precision_loss,
    clippy::as_conversions,
)]

use std::process::Command;

use safetensors::{Dtype, View, serialize_to_file};
use tempfile::TempDir;

struct Tensor {
    dtype: Dtype,
    shape: Vec<usize>,
    data: Vec<u8>,
}

impl View for &Tensor {
    fn dtype(&self) -> Dtype {
        self.dtype
    }
    fn shape(&self) -> &[usize] {
        &self.shape
    }
    fn data(&self) -> std::borrow::Cow<'_, [u8]> {
        std::borrow::Cow::Borrowed(&self.data)
    }
    fn data_len(&self) -> usize {
        self.data.len()
    }
}

fn f32_tensor(shape: Vec<usize>, values: &[f32]) -> Tensor {
    let mut data = Vec::with_capacity(values.len() * 4);
    for v in values {
        data.extend_from_slice(&v.to_le_bytes());
    }
    Tensor {
        dtype: Dtype::F32,
        shape,
        data,
    }
}

#[test]
fn acceptance_ac1() {
    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("model.safetensors");
    let out_path = dir.path().join("weights.rs");

    let w_ih: Vec<f32> = (0..12).map(|i| i as f32).collect();
    let tensors: Vec<(String, Tensor)> = vec![
        ("lstm.w_ih".to_string(), f32_tensor(vec![4, 3], &w_ih)),
        ("lstm.b".to_string(), f32_tensor(vec![5], &[0.1, 0.2, 0.3, 0.4, 0.5])),
    ];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let out = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "lstm",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();

    assert!(
        out.status.success(),
        "expected exit 0, got {:?}: stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );

    let src = std::fs::read_to_string(&out_path).unwrap();
    assert!(src.contains("pub const LSTM_W_IH: [[f32; 3]; 4]"), "missing 2D const:\n{src}");
    assert!(src.contains("pub const LSTM_B: [f32; 5]"), "missing 1D const:\n{src}");
    assert!(
        src.contains("pub const ARCH_FINGERPRINT: &str = \"lstm-"),
        "missing/malformed ARCH_FINGERPRINT:\n{src}"
    );
    assert!(src.contains("-v1\";"), "fingerprint must end with -v1:\n{src}");
}
