//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: The emitted `.rs` file compiles standalone (no morsel runtime deps). The test writes the output to a tempdir, wraps it in a minimal `Cargo.toml`+`lib.rs`, runs `cargo build`, and asserts success.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::cast_precision_loss,
    clippy::as_conversions,
)]

use std::process::Command;

use safetensors::{Dtype, View, serialize_to_file};
use tempfile::TempDir;

struct Tensor {
    dtype: Dtype,
    shape: Vec<usize>,
    data: Vec<u8>,
}

impl View for &Tensor {
    fn dtype(&self) -> Dtype { self.dtype }
    fn shape(&self) -> &[usize] { &self.shape }
    fn data(&self) -> std::borrow::Cow<'_, [u8]> { std::borrow::Cow::Borrowed(&self.data) }
    fn data_len(&self) -> usize { self.data.len() }
}

fn f32_tensor(shape: Vec<usize>, values: &[f32]) -> Tensor {
    let mut data = Vec::with_capacity(values.len() * 4);
    for v in values {
        data.extend_from_slice(&v.to_le_bytes());
    }
    Tensor { dtype: Dtype::F32, shape, data }
}

#[test]
fn acceptance_ac3() {
    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("smoke.safetensors");

    // Build a smoke crate at <dir>/smoke/.
    let crate_dir = dir.path().join("smoke");
    let src_dir = crate_dir.join("src");
    std::fs::create_dir_all(&src_dir).unwrap();
    let weights_path = src_dir.join("weights.rs");

    // Mix of ranks to exercise the nested-array emitter.
    let cube_vals: Vec<f32> = (0..8).map(|i| i as f32).collect();
    let tensors: Vec<(String, Tensor)> = vec![
        ("scalar".to_string(), f32_tensor(vec![], &[3.5])),
        ("vec".to_string(), f32_tensor(vec![3], &[1.0, 2.0, 3.0])),
        ("mat".to_string(), f32_tensor(vec![2, 2], &[1.0, 2.0, 3.0, 4.0])),
        ("cube".to_string(), f32_tensor(vec![2, 2, 2], &cube_vals)),
    ];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let bake = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "smoke",
            "--out", weights_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(bake.status.success(), "bake failed: {}", String::from_utf8_lossy(&bake.stderr));

    // Minimal wrapper Cargo.toml + lib.rs.
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        r#"[package]
name = "smoke"
version = "0.0.1"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
"#,
    ).unwrap();
    // Load weights.rs as a real module file (not include!), so the
    // emitted `//!` header is interpreted as the module's own inner
    // doc comment — legal at the top of a `.rs` module file.
    std::fs::write(
        src_dir.join("lib.rs"),
        "#[path = \"weights.rs\"]\npub mod weights;\n",
    ).unwrap();

    let target_dir = dir.path().join("smoke-target");
    let build = Command::new("cargo")
        .args(["build", "--manifest-path"])
        .arg(crate_dir.join("Cargo.toml"))
        .args(["--target-dir"])
        .arg(&target_dir)
        .output()
        .unwrap();

    assert!(
        build.status.success(),
        "smoke crate failed to build:\nstdout:\n{}\nstderr:\n{}\n--- emitted ---\n{}",
        String::from_utf8_lossy(&build.stdout),
        String::from_utf8_lossy(&build.stderr),
        std::fs::read_to_string(&weights_path).unwrap_or_default(),
    );
}
