//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Non-existent --in file → exit 2 with stderr containing the path and `safetensors file not found`. --out path that already exists → exit 7 unless `--force` is passed (then overwrites).
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

use safetensors::{Dtype, View, serialize_to_file};
use tempfile::TempDir;

struct Tensor {
    dtype: Dtype,
    shape: Vec<usize>,
    data: Vec<u8>,
}

impl View for &Tensor {
    fn dtype(&self) -> Dtype { self.dtype }
    fn shape(&self) -> &[usize] { &self.shape }
    fn data(&self) -> std::borrow::Cow<'_, [u8]> { std::borrow::Cow::Borrowed(&self.data) }
    fn data_len(&self) -> usize { self.data.len() }
}

fn f32_tensor(shape: Vec<usize>, values: &[f32]) -> Tensor {
    let mut data = Vec::with_capacity(values.len() * 4);
    for v in values {
        data.extend_from_slice(&v.to_le_bytes());
    }
    Tensor { dtype: Dtype::F32, shape, data }
}

#[test]
fn ac7_missing_input_exits_2() {
    let dir = TempDir::new().unwrap();
    let missing = dir.path().join("nope.safetensors");
    let out_path = dir.path().join("o.rs");

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let out = Command::new(bin)
        .args([
            "--in", missing.to_str().unwrap(),
            "--arch", "x",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();

    assert_eq!(
        out.status.code(),
        Some(2),
        "expected exit 2 for missing input, got {:?}",
        out.status
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("safetensors file not found"),
        "stderr missing message:\n{stderr}"
    );
    assert!(
        stderr.contains("nope.safetensors"),
        "stderr missing path:\n{stderr}"
    );
}

#[test]
fn acceptance_ac7() {
    // The headline AC7 case: --out exists & no --force = exit 7,
    // and --force overwrites.
    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("in.safetensors");
    let out_path = dir.path().join("out.rs");

    let tensors: Vec<(String, Tensor)> = vec![("a".to_string(), f32_tensor(vec![1], &[1.5]))];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    // Pre-create the output file with sentinel content.
    std::fs::write(&out_path, "// pre-existing sentinel\n").unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");

    // 1) Without --force → exit 7, file unchanged.
    let out = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "x",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(7),
        "expected exit 7 for existing output, got {:?}, stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    let after = std::fs::read_to_string(&out_path).unwrap();
    assert_eq!(after, "// pre-existing sentinel\n", "sentinel was clobbered without --force");

    // 2) With --force → success, sentinel replaced.
    let out2 = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "x",
            "--out", out_path.to_str().unwrap(),
            "--force",
        ])
        .output()
        .unwrap();
    assert!(out2.status.success(), "force-bake failed: {}", String::from_utf8_lossy(&out2.stderr));
    let after2 = std::fs::read_to_string(&out_path).unwrap();
    assert!(after2.contains("pub const A:"), "force-bake didn't write expected content:\n{after2}");
    assert!(!after2.contains("sentinel"), "force-bake left old content:\n{after2}");
}
