//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Tensors with rank > 2 are emitted as Rust nested arrays one dimension deeper per rank (`[[[f32; D2]; D1]; D0]`). Rank-0 (scalar) tensors emit `pub const NAME: f32 = ...;`. Rank > 4 → exit 6 with stderr `rank N exceeds supported max 4`.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::cast_precision_loss,
    clippy::as_conversions,
)]

use std::process::Command;

use safetensors::{Dtype, View, serialize_to_file};
use tempfile::TempDir;

struct Tensor {
    dtype: Dtype,
    shape: Vec<usize>,
    data: Vec<u8>,
}

impl View for &Tensor {
    fn dtype(&self) -> Dtype { self.dtype }
    fn shape(&self) -> &[usize] { &self.shape }
    fn data(&self) -> std::borrow::Cow<'_, [u8]> { std::borrow::Cow::Borrowed(&self.data) }
    fn data_len(&self) -> usize { self.data.len() }
}

fn f32_tensor(shape: Vec<usize>, values: &[f32]) -> Tensor {
    let mut data = Vec::with_capacity(values.len() * 4);
    for v in values {
        data.extend_from_slice(&v.to_le_bytes());
    }
    Tensor { dtype: Dtype::F32, shape, data }
}

#[test]
fn ac6_ranks_0_to_4_emit() {
    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("ranks.safetensors");
    let out_path = dir.path().join("ranks.rs");

    let c_vals: Vec<f32> = (0..8).map(|i| i as f32).collect();
    let t_vals: Vec<f32> = (0..16).map(|i| i as f32).collect();
    let tensors: Vec<(String, Tensor)> = vec![
        ("s".to_string(), f32_tensor(vec![], &[0.5])),
        ("v".to_string(), f32_tensor(vec![3], &[1.0, 2.0, 3.0])),
        ("m".to_string(), f32_tensor(vec![2, 2], &[1.0, 2.0, 3.0, 4.0])),
        ("c".to_string(), f32_tensor(vec![2, 2, 2], &c_vals)),
        ("t".to_string(), f32_tensor(vec![2, 2, 2, 2], &t_vals)),
    ];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let out = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "ranks",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(out.status.success(), "stderr={}", String::from_utf8_lossy(&out.stderr));

    let src = std::fs::read_to_string(&out_path).unwrap();
    assert!(src.contains("pub const S: f32 ="), "rank-0 not emitted as scalar:\n{src}");
    assert!(src.contains("pub const V: [f32; 3]"), "rank-1 wrong type:\n{src}");
    assert!(src.contains("pub const M: [[f32; 2]; 2]"), "rank-2 wrong type:\n{src}");
    assert!(src.contains("pub const C: [[[f32; 2]; 2]; 2]"), "rank-3 wrong type:\n{src}");
    assert!(src.contains("pub const T: [[[[f32; 2]; 2]; 2]; 2]"), "rank-4 wrong type:\n{src}");
}

#[test]
fn acceptance_ac6() {
    // Rank-5 must be rejected with exit 6 and exact phrasing.
    let dir = TempDir::new().unwrap();
    let st_path = dir.path().join("rank5.safetensors");
    let out_path = dir.path().join("rank5.rs");

    let shape = vec![2, 2, 2, 2, 2];
    let n: usize = shape.iter().product();
    let tensors: Vec<(String, Tensor)> = vec![(
        "huge".to_string(),
        f32_tensor(shape, &vec![0.0_f32; n]),
    )];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st_path).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");
    let out = Command::new(bin)
        .args([
            "--in", st_path.to_str().unwrap(),
            "--arch", "x",
            "--out", out_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();

    assert_eq!(
        out.status.code(),
        Some(6),
        "expected exit 6, got {:?}, stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("rank 5 exceeds supported max 4"),
        "stderr missing exact phrasing:\n{stderr}"
    );
}
