//! Acceptance test for AC8 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Emitted file includes a `//! generated by morsel-bake v<crate-version> from <input-basename> @ <RFC3339>` doc header. The header is excluded from any byte-level diff testing (commented out via `cfg`-style sentinels), so re-baking the same input produces a stable file modulo the header.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::manual_split_once,
)]

use std::process::Command;

use safetensors::{Dtype, View, serialize_to_file};
use tempfile::TempDir;

struct Tensor {
    dtype: Dtype,
    shape: Vec<usize>,
    data: Vec<u8>,
}

impl View for &Tensor {
    fn dtype(&self) -> Dtype { self.dtype }
    fn shape(&self) -> &[usize] { &self.shape }
    fn data(&self) -> std::borrow::Cow<'_, [u8]> { std::borrow::Cow::Borrowed(&self.data) }
    fn data_len(&self) -> usize { self.data.len() }
}

fn f32_tensor(shape: Vec<usize>, values: &[f32]) -> Tensor {
    let mut data = Vec::with_capacity(values.len() * 4);
    for v in values {
        data.extend_from_slice(&v.to_le_bytes());
    }
    Tensor { dtype: Dtype::F32, shape, data }
}

fn bake_one(bin: &str, st: &std::path::Path, out: &std::path::Path, stamp: Option<&str>, force: bool) {
    let mut cmd = Command::new(bin);
    cmd.args([
        "--in", st.to_str().unwrap(),
        "--arch", "x",
        "--out", out.to_str().unwrap(),
    ]);
    if force {
        cmd.arg("--force");
    }
    if let Some(s) = stamp {
        cmd.args(["--source-stamp", s]);
    }
    let res = cmd.output().unwrap();
    assert!(res.status.success(), "bake failed: {}", String::from_utf8_lossy(&res.stderr));
}

#[test]
fn acceptance_ac8() {
    let dir = TempDir::new().unwrap();
    let st = dir.path().join("hdr.safetensors");
    let out_a = dir.path().join("a.rs");
    let out_b = dir.path().join("b.rs");

    let tensors: Vec<(String, Tensor)> = vec![("w".to_string(), f32_tensor(vec![2, 2], &[1.0, 2.0, 3.0, 4.0]))];
    serialize_to_file(tensors.iter().map(|(s, t)| (s.as_str(), t)), None, &st).unwrap();

    let bin = env!("CARGO_BIN_EXE_morsel-bake");

    // 1) First bake: assert header shape.
    bake_one(bin, &st, &out_a, None, false);
    let src = std::fs::read_to_string(&out_a).unwrap();
    let first = src.lines().next().unwrap_or("");
    assert!(
        first.starts_with("//! generated by morsel-bake v"),
        "header prefix wrong: {first}"
    );
    assert!(first.contains(" from hdr.safetensors @ "), "header basename/stamp wrong: {first}");
    let version = env!("CARGO_PKG_VERSION");
    assert!(first.contains(&format!("v{version}")), "header version wrong (want v{version}): {first}");

    // 2) Stable rebake with --source-stamp: byte-identical, including header.
    bake_one(bin, &st, &out_a, Some("2026-01-01T00:00:00Z"), true);
    bake_one(bin, &st, &out_b, Some("2026-01-01T00:00:00Z"), false);
    let a = std::fs::read(&out_a).unwrap();
    let b = std::fs::read(&out_b).unwrap();
    assert_eq!(a, b, "byte-stable rebake with fixed source-stamp should be identical");

    // 3) Modulo-header check: strip first line, compare two bakes with
    //    different (real) stamps. Body must match.
    let out_c = dir.path().join("c.rs");
    let out_d = dir.path().join("d.rs");
    bake_one(bin, &st, &out_c, Some("2026-01-01T00:00:00Z"), false);
    bake_one(bin, &st, &out_d, Some("2030-12-31T23:59:59Z"), false);
    let strip_first_line = |s: String| -> String {
        s.splitn(2, '\n').nth(1).unwrap_or("").to_string()
    };
    let c_body = strip_first_line(std::fs::read_to_string(&out_c).unwrap());
    let d_body = strip_first_line(std::fs::read_to_string(&out_d).unwrap());
    assert_eq!(c_body, d_body, "body differs under different stamps");
}
