//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: agorabus (cli)
//! AC description: Fail-open client: `agorabus peers` with no daemon running exits 0 and emits `[]` on stdout (PRD risk-mitigation requirement). All client subcommands treat connection-refused / no-socket as 'no peers / no bus' rather than as a hard error.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::cast_lossless, clippy::cast_possible_truncation, clippy::cast_sign_loss, clippy::missing_panics_doc, clippy::many_single_char_names, clippy::as_conversions, clippy::panic, clippy::needless_pass_by_value, clippy::similar_names, clippy::tests_outside_test_module, clippy::needless_borrow)]

use std::process::Command;

#[test]
fn acceptance_ac6() {
    // No daemon running on this socket; the file does not exist.
    let tmp = tempfile::tempdir().unwrap();
    let nonexistent = tmp.path().join("absent.sock");

    let bin = env!("CARGO_BIN_EXE_agorabus");

    // (a) `agorabus peers --socket <nonexistent>` exits 0 with stdout == "[]\n".
    let out = Command::new(bin)
        .arg("--socket")
        .arg(&nonexistent)
        .arg("peers")
        .output()
        .expect("spawn agorabus peers");
    assert!(
        out.status.success(),
        "peers should fail-open: status={:?} stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert_eq!(
        stdout.trim(),
        "[]",
        "peers should emit empty JSON array, got {stdout:?}"
    );

    // (b) `agorabus announce ...` also exits 0 (no-op).
    let out = Command::new(bin)
        .arg("--socket")
        .arg(&nonexistent)
        .args(["announce", "--session-id", "x", "--cwd", "/", "--intent", ""])
        .output()
        .expect("spawn agorabus announce");
    assert!(
        out.status.success(),
        "announce should fail-open: status={:?} stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );

    // (c) `agorabus publish` also exits 0.
    let out = Command::new(bin)
        .arg("--socket")
        .arg(&nonexistent)
        .args(["publish", "shared.test", "\"hi\""])
        .output()
        .expect("spawn agorabus publish");
    assert!(
        out.status.success(),
        "publish should fail-open: status={:?} stderr={}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
}
