//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: `self-portrait extract --file <repo-relative-path> [--repo <dir>]` emits a single JSON object on stdout: `{file, repo, generated_at, commits: [...]}`. Each commit entry has: hash (full sha), short_hash (7 chars), author_name, author_email, committed_at (RFC3339), subject, body, diff (unified diff hunk for this file across this commit, file headers stripped). Order: oldest commit first.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature};
use tempfile::TempDir;

fn init_repo(dir: &Path) -> Repository {
    Repository::init(dir).unwrap()
}

fn commit_file(
    repo: &Repository,
    dir: &Path,
    path: &str,
    contents: &[u8],
    author_name: &str,
    author_email: &str,
    msg: &str,
    when_secs: i64,
) {
    fs::write(dir.join(path), contents).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(Path::new(path)).unwrap();
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new(author_name, author_email, &git2::Time::new(when_secs, 0)).unwrap();
    let parent = repo
        .head()
        .ok()
        .and_then(|h| h.peel_to_commit().ok());
    let parents: Vec<&git2::Commit<'_>> = parent.iter().collect();
    repo.commit(Some("HEAD"), &sig, &sig, msg, &tree, &parents)
        .unwrap();
}

#[test]
fn acceptance_ac1() {
    let tmp = TempDir::new().unwrap();
    let repo = init_repo(tmp.path());
    commit_file(
        &repo,
        tmp.path(),
        "NOTES.md",
        b"alpha\n",
        "Alice",
        "alice@example.com",
        "init notes",
        1_700_000_000,
    );
    commit_file(
        &repo,
        tmp.path(),
        "NOTES.md",
        b"alpha\nbeta\n",
        "Bob",
        "bob@example.com",
        "add beta",
        1_700_000_100,
    );

    let bin = env!("CARGO_BIN_EXE_self-portrait");
    let out = Command::new(bin)
        .args(["extract", "--file", "NOTES.md", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(parsed["file"], "NOTES.md");
    let repo_field = parsed["repo"].as_str().unwrap();
    assert!(
        Path::new(repo_field).is_absolute(),
        "repo field must be absolute: {repo_field}"
    );
    chrono::DateTime::parse_from_rfc3339(parsed["generated_at"].as_str().unwrap()).unwrap();

    let commits = parsed["commits"].as_array().unwrap();
    assert_eq!(commits.len(), 2);

    // Oldest first.
    let first = &commits[0];
    let second = &commits[1];
    assert_eq!(first["subject"], "init notes");
    assert_eq!(second["subject"], "add beta");
    assert_eq!(first["author_name"], "Alice");
    assert_eq!(first["author_email"], "alice@example.com");
    assert_eq!(second["author_name"], "Bob");

    // Full + short hash sanity.
    let hash = first["hash"].as_str().unwrap();
    let short = first["short_hash"].as_str().unwrap();
    assert_eq!(hash.len(), 40);
    assert_eq!(short.len(), 7);
    assert!(hash.starts_with(short));

    // RFC3339 sanity.
    chrono::DateTime::parse_from_rfc3339(first["committed_at"].as_str().unwrap()).unwrap();

    // Diff present, file headers stripped.
    let diff = second["diff"].as_str().unwrap();
    assert!(!diff.is_empty());
    assert!(
        !diff.contains("diff --git"),
        "file header should be stripped: {diff}"
    );
    assert!(!diff.contains("index "), "index header should be stripped: {diff}");
    assert!(!diff.contains("--- a/"), "minus header should be stripped: {diff}");
    assert!(!diff.contains("+++ b/"), "plus header should be stripped: {diff}");
    assert!(diff.contains("+beta"), "diff should contain the +beta hunk: {diff}");
}
