//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: When the file does not exist in the current HEAD but did historically (e.g. it was deleted), the extractor still walks the history — exits 0 with all commits in `commits` and a top-level `"deleted_at": "<RFC3339>"` field. If the file never existed under any name, exits with code 3 and stderr containing the path and `no commits found`.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature};
use tempfile::TempDir;

fn init_repo(dir: &Path) -> Repository {
    Repository::init(dir).unwrap()
}

fn commit_with_index(
    repo: &Repository,
    msg: &str,
    when_secs: i64,
) {
    let mut index = repo.index().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Alice", "alice@example.com", &git2::Time::new(when_secs, 0)).unwrap();
    let parent = repo
        .head()
        .ok()
        .and_then(|h| h.peel_to_commit().ok());
    let parents: Vec<&git2::Commit<'_>> = parent.iter().collect();
    repo.commit(Some("HEAD"), &sig, &sig, msg, &tree, &parents)
        .unwrap();
}

#[test]
fn deleted_file_walks_history_with_deleted_at() {
    let tmp = TempDir::new().unwrap();
    let repo = init_repo(tmp.path());

    // Create, modify, then delete the file. After deletion HEAD has
    // no `gone.md` but history must still surface 3 commits and the
    // top-level `deleted_at`.
    fs::write(tmp.path().join("gone.md"), b"alpha\n").unwrap();
    {
        let mut index = repo.index().unwrap();
        index.add_path(Path::new("gone.md")).unwrap();
        index.write().unwrap();
    }
    commit_with_index(&repo, "create gone.md", 1_700_000_000);

    fs::write(tmp.path().join("gone.md"), b"alpha\nbeta\n").unwrap();
    {
        let mut index = repo.index().unwrap();
        index.add_path(Path::new("gone.md")).unwrap();
        index.write().unwrap();
    }
    commit_with_index(&repo, "extend gone.md", 1_700_000_100);

    fs::remove_file(tmp.path().join("gone.md")).unwrap();
    {
        let mut index = repo.index().unwrap();
        index.remove_path(Path::new("gone.md")).unwrap();
        index.write().unwrap();
    }
    // Need at least one other file present so the tree isn't empty.
    fs::write(tmp.path().join("keep.md"), b"keep\n").unwrap();
    {
        let mut index = repo.index().unwrap();
        index.add_path(Path::new("keep.md")).unwrap();
        index.write().unwrap();
    }
    commit_with_index(&repo, "remove gone.md, add keep.md", 1_700_000_200);

    let bin = env!("CARGO_BIN_EXE_self-portrait");
    let out = Command::new(bin)
        .args(["extract", "--file", "gone.md", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let commits = parsed["commits"].as_array().unwrap();
    assert_eq!(commits.len(), 3, "all three commits that touched gone.md must appear");
    let deleted_at = parsed["deleted_at"].as_str().unwrap_or("");
    assert!(!deleted_at.is_empty(), "deleted_at must be populated");
    chrono::DateTime::parse_from_rfc3339(deleted_at).unwrap();
}

#[test]
fn file_never_existed_exits_three() {
    let tmp = TempDir::new().unwrap();
    let repo = init_repo(tmp.path());
    fs::write(tmp.path().join("README.md"), b"hello\n").unwrap();
    {
        let mut index = repo.index().unwrap();
        index.add_path(Path::new("README.md")).unwrap();
        index.write().unwrap();
    }
    commit_with_index(&repo, "init", 1_700_000_000);

    let bin = env!("CARGO_BIN_EXE_self-portrait");
    let out = Command::new(bin)
        .args(["extract", "--file", "never-existed.md", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(3));
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("never-existed.md") && stderr.contains("no commits found"),
        "stderr should mention path and 'no commits found': {stderr}"
    );
}
