//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: When `--repo <dir>` points at a non-git path: exit code 2 with stderr containing the path and `not a git repository`.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

use tempfile::TempDir;

#[test]
fn acceptance_ac5() {
    let tmp = TempDir::new().unwrap();
    // tmp.path() is a real, existing directory but not a git repo.

    let bin = env!("CARGO_BIN_EXE_self-portrait");
    let out = Command::new(bin)
        .args(["extract", "--file", "README.md", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(2),
        "stdout: {} stderr: {}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    let path_str = tmp.path().display().to_string();
    assert!(
        stderr.contains(&path_str),
        "stderr should mention the path {path_str}: {stderr}"
    );
    assert!(
        stderr.contains("not a git repository"),
        "stderr should contain 'not a git repository': {stderr}"
    );
}
