//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: Follows file renames via git's --follow semantics — a commit that renamed the file appears in the commits array, with `diff` containing the rename hunk.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature};
use tempfile::TempDir;

fn init_repo(dir: &Path) -> Repository {
    Repository::init(dir).unwrap()
}

fn commit_with_index(
    repo: &Repository,
    msg: &str,
    when_secs: i64,
) {
    let mut index = repo.index().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Alice", "alice@example.com", &git2::Time::new(when_secs, 0)).unwrap();
    let parent = repo
        .head()
        .ok()
        .and_then(|h| h.peel_to_commit().ok());
    let parents: Vec<&git2::Commit<'_>> = parent.iter().collect();
    repo.commit(Some("HEAD"), &sig, &sig, msg, &tree, &parents)
        .unwrap();
}

#[test]
fn acceptance_ac2() {
    let tmp = TempDir::new().unwrap();
    let repo = init_repo(tmp.path());

    // Commit 1: create OLD.md with significant content (rename
    // detection wants enough content to score as similar).
    fs::write(
        tmp.path().join("OLD.md"),
        b"line1\nline2\nline3\nline4\nline5\n",
    )
    .unwrap();
    {
        let mut index = repo.index().unwrap();
        index.add_path(Path::new("OLD.md")).unwrap();
        index.write().unwrap();
    }
    commit_with_index(&repo, "create OLD.md", 1_700_000_000);

    // Commit 2: rename OLD.md → NEW.md (identical content).
    fs::remove_file(tmp.path().join("OLD.md")).unwrap();
    fs::write(
        tmp.path().join("NEW.md"),
        b"line1\nline2\nline3\nline4\nline5\n",
    )
    .unwrap();
    {
        let mut index = repo.index().unwrap();
        index.remove_path(Path::new("OLD.md")).unwrap();
        index.add_path(Path::new("NEW.md")).unwrap();
        index.write().unwrap();
    }
    commit_with_index(&repo, "rename OLD.md to NEW.md", 1_700_000_100);

    // Commit 3: modify NEW.md.
    fs::write(
        tmp.path().join("NEW.md"),
        b"line1\nline2\nline3\nline4\nline5\nline6\n",
    )
    .unwrap();
    {
        let mut index = repo.index().unwrap();
        index.add_path(Path::new("NEW.md")).unwrap();
        index.write().unwrap();
    }
    commit_with_index(&repo, "extend NEW.md", 1_700_000_200);

    let bin = env!("CARGO_BIN_EXE_self-portrait");
    let out = Command::new(bin)
        .args(["extract", "--file", "NEW.md", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let commits = parsed["commits"].as_array().unwrap();
    // Should have 3 entries: the original create, the rename, the modify.
    assert_eq!(
        commits.len(),
        3,
        "expected to follow rename and surface 3 commits, got {}: {commits:?}",
        commits.len()
    );

    let subjects: Vec<&str> = commits
        .iter()
        .map(|c| c["subject"].as_str().unwrap())
        .collect();
    assert_eq!(
        subjects,
        vec!["create OLD.md", "rename OLD.md to NEW.md", "extend NEW.md"]
    );

    // The rename commit's diff should mention either "rename" or the
    // old path "OLD.md" (libgit2's rename hunk includes a `rename from`
    // header). Either signal is acceptable evidence of the rename.
    let rename_diff = commits[1]["diff"].as_str().unwrap();
    assert!(
        rename_diff.contains("rename") || rename_diff.contains("OLD.md"),
        "rename commit diff should contain rename evidence: {rename_diff}"
    );
}
