//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: Commits that touched the file with a trivial change (no semantic diff after the rename) still appear and their `diff` is included verbatim; the consumer decides whether to collapse them. The extractor does not editorialize.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature};
use tempfile::TempDir;

fn init_repo(dir: &Path) -> Repository {
    Repository::init(dir).unwrap()
}

fn commit_file(
    repo: &Repository,
    dir: &Path,
    path: &str,
    contents: &[u8],
    msg: &str,
    when_secs: i64,
) {
    fs::write(dir.join(path), contents).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(Path::new(path)).unwrap();
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Alice", "alice@example.com", &git2::Time::new(when_secs, 0)).unwrap();
    let parent = repo
        .head()
        .ok()
        .and_then(|h| h.peel_to_commit().ok());
    let parents: Vec<&git2::Commit<'_>> = parent.iter().collect();
    repo.commit(Some("HEAD"), &sig, &sig, msg, &tree, &parents)
        .unwrap();
}

#[test]
fn acceptance_ac3() {
    let tmp = TempDir::new().unwrap();
    let repo = init_repo(tmp.path());

    // Three commits: substantive, then trailing-whitespace (trivial),
    // then substantive again. All three must appear; the trivial one's
    // `diff` must be present verbatim (not redacted, not removed).
    commit_file(
        &repo,
        tmp.path(),
        "notes.md",
        b"alpha\nbeta\n",
        "init",
        1_700_000_000,
    );
    commit_file(
        &repo,
        tmp.path(),
        "notes.md",
        b"alpha\nbeta\n   \n",
        "add trailing whitespace line",
        1_700_000_100,
    );
    commit_file(
        &repo,
        tmp.path(),
        "notes.md",
        b"alpha\nbeta\n   \ngamma\n",
        "add gamma",
        1_700_000_200,
    );

    let bin = env!("CARGO_BIN_EXE_self-portrait");
    let out = Command::new(bin)
        .args(["extract", "--file", "notes.md", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));

    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let commits = parsed["commits"].as_array().unwrap();
    assert_eq!(commits.len(), 3, "trivial commit must still appear");

    let subjects: Vec<&str> = commits
        .iter()
        .map(|c| c["subject"].as_str().unwrap())
        .collect();
    assert_eq!(
        subjects,
        vec!["init", "add trailing whitespace line", "add gamma"]
    );

    // The "trivial" middle commit must have a non-empty diff verbatim
    // (default mode does not collapse — AC7 is opt-in).
    let trivial_diff = commits[1]["diff"].as_str().unwrap();
    assert!(
        !trivial_diff.is_empty(),
        "AC3 forbids editorializing — diff must be present verbatim"
    );
    assert!(
        trivial_diff.contains('+'),
        "the +<whitespace> line should appear in the diff: {trivial_diff}"
    );
}
