//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: `--collapse-trivial` collapses commits whose `diff` body, after stripping whitespace/comments, is empty into a single virtual `{hash: "trivial", subject: "N trivial edits", ...}` adjacent entry; default is no collapse (AC3).
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::path::Path;
use std::process::Command;

use git2::{Repository, Signature};
use tempfile::TempDir;

fn init_repo(dir: &Path) -> Repository {
    Repository::init(dir).unwrap()
}

fn commit_file(
    repo: &Repository,
    dir: &Path,
    path: &str,
    contents: &[u8],
    msg: &str,
    when_secs: i64,
) {
    fs::write(dir.join(path), contents).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(Path::new(path)).unwrap();
    index.write().unwrap();
    let tree_oid = index.write_tree().unwrap();
    let tree = repo.find_tree(tree_oid).unwrap();
    let sig = Signature::new("Alice", "alice@example.com", &git2::Time::new(when_secs, 0)).unwrap();
    let parent = repo
        .head()
        .ok()
        .and_then(|h| h.peel_to_commit().ok());
    let parents: Vec<&git2::Commit<'_>> = parent.iter().collect();
    repo.commit(Some("HEAD"), &sig, &sig, msg, &tree, &parents)
        .unwrap();
}

#[test]
fn acceptance_ac7() {
    let tmp = TempDir::new().unwrap();
    let repo = init_repo(tmp.path());

    // Substantive, 2 trivial (whitespace-only), substantive, 1 trivial.
    commit_file(&repo, tmp.path(), "notes.md", b"alpha\n", "init", 1_700_000_000);
    commit_file(
        &repo,
        tmp.path(),
        "notes.md",
        b"alpha\n   \n",
        "whitespace 1",
        1_700_000_100,
    );
    commit_file(
        &repo,
        tmp.path(),
        "notes.md",
        b"alpha\n   \n\t\n",
        "whitespace 2",
        1_700_000_200,
    );
    commit_file(
        &repo,
        tmp.path(),
        "notes.md",
        b"alpha\n   \n\t\nbeta\n",
        "add beta",
        1_700_000_300,
    );
    commit_file(
        &repo,
        tmp.path(),
        "notes.md",
        b"alpha\n   \n\t\nbeta\n  \n",
        "whitespace 3",
        1_700_000_400,
    );

    let bin = env!("CARGO_BIN_EXE_self-portrait");

    // Without --collapse-trivial: 5 entries, all present (AC3 default).
    let out_default = Command::new(bin)
        .args(["extract", "--file", "notes.md", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(out_default.status.code(), Some(0));
    let parsed_default: serde_json::Value = serde_json::from_slice(&out_default.stdout).unwrap();
    assert_eq!(parsed_default["commits"].as_array().unwrap().len(), 5);

    // With --collapse-trivial: 5 → 3 (substantive, {2 trivial}, substantive, {1 trivial}).
    let out_collapsed = Command::new(bin)
        .args(["extract", "--file", "notes.md", "--collapse-trivial", "--repo"])
        .arg(tmp.path())
        .output()
        .unwrap();
    assert_eq!(
        out_collapsed.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out_collapsed.stderr)
    );
    let parsed: serde_json::Value = serde_json::from_slice(&out_collapsed.stdout).unwrap();
    let commits = parsed["commits"].as_array().unwrap();
    assert_eq!(
        commits.len(),
        4,
        "expected 4 entries (init, trivial-run-of-2, add-beta, trivial-run-of-1): {commits:?}"
    );

    // Entry 0 (init) is substantive.
    assert_eq!(commits[0]["subject"], "init");
    assert_ne!(commits[0]["hash"].as_str().unwrap(), "trivial");

    // Entry 1 is the collapsed run of 2 trivial edits.
    assert_eq!(commits[1]["hash"], "trivial");
    assert_eq!(commits[1]["short_hash"], "trivial");
    assert_eq!(commits[1]["subject"], "2 trivial edits");

    // Entry 2 is the substantive "add beta".
    assert_eq!(commits[2]["subject"], "add beta");

    // Entry 3 is the collapsed singleton trivial run.
    assert_eq!(commits[3]["hash"], "trivial");
    assert_eq!(commits[3]["subject"], "1 trivial edits");
}
