//! Acceptance test for AC9 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: Exit codes: 0 = success; 1 = expected-failure (orphaned end event reported, stale skill found with --strict); 2 = invocation error (bad args, unreadable root, unwritable journal).
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac9() {
    let bin = env!("CARGO_BIN_EXE_spool");
    let root = TempDir::new().unwrap();

    // 0: success path
    let out = Command::new(bin)
        .args(["log", "start", "x", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));

    // 1: orphan end
    let out = Command::new(bin)
        .args(["log", "end", "01NOTREAL00000000000000000", "--outcome", "ok", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));

    // 2: bad outcome value (validation error)
    let out = Command::new(bin)
        .args(["log", "end", "01XXX", "--outcome", "nonsense", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));

    // 2: unknown subcommand
    let out = Command::new(bin).arg("not-a-subcommand").output().unwrap();
    assert_eq!(out.status.code(), Some(2));
}
