//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: Robust to incomplete pairs: a `start` without matching `end` shows in `rank` with `mean_ms_or_null: null` and is still counted as an invocation. An `end` without start is reported on stderr as orphaned but does not crash.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac7() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_spool");

    // Start only — no end.
    Command::new(bin)
        .args(["log", "start", "noisy-skill", "--root"])
        .arg(root.path())
        .output()
        .unwrap();

    // Rank should include it with mean_ms absent / null.
    let out = Command::new(bin)
        .args(["rank", "--format", "json", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    let parsed: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let arr = parsed.as_array().unwrap();
    let entry = arr.iter().find(|e| e["skill"] == "noisy-skill").unwrap();
    assert_eq!(entry["invocations"], 1);
    assert!(entry["mean_ms"].is_null() || entry.get("mean_ms").is_none());

    // End-without-start: writes the orphan to journal, exits with code 1.
    let out = Command::new(bin)
        .args(["log", "end", "01ORPHAN00000000000000000Z", "--outcome", "ok", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));
    let stderr = String::from_utf8(out.stderr).unwrap();
    assert!(stderr.contains("orphan"), "stderr must mention orphan: {stderr}");
}
