//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: `spool log start <skill> --args <text>` truncates `args` to 200 chars (after which a `…` is appended). The truncation is recorded as `args_truncated: true` when applied.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac8() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_spool");

    // Short args: no truncation.
    Command::new(bin)
        .args(["log", "start", "x", "--args", "short", "--root"])
        .arg(root.path())
        .output()
        .unwrap();

    // Long args: 500 chars → must truncate.
    let long_args: String = "a".repeat(500);
    Command::new(bin)
        .args(["log", "start", "y", "--args", &long_args, "--root"])
        .arg(root.path())
        .output()
        .unwrap();

    let path = std::fs::read_dir(root.path())
        .unwrap()
        .filter_map(Result::ok)
        .map(|e| e.path())
        .next()
        .unwrap();
    let content = std::fs::read_to_string(path).unwrap();
    let lines: Vec<&str> = content.lines().collect();
    let line1: serde_json::Value = serde_json::from_str(lines[0]).unwrap();
    assert_eq!(line1["args"], "short");
    assert!(line1.get("args_truncated").is_none_or(|v| v == false));

    let line2: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
    let truncated = line2["args"].as_str().unwrap();
    assert_eq!(truncated.chars().count(), 200);
    assert!(truncated.ends_with('…'));
    assert_eq!(line2["args_truncated"], true);
}
