//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: Empty `<root>` directory (no JSONL files): `spool rank` exits 0 with an empty table (header row only); `spool report --stale 30d` exits 0 with no output.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac10() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_spool");

    let out = Command::new(bin).args(["rank", "--root"]).arg(root.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert_eq!(stdout.lines().count(), 1, "header only: {stdout}");

    let out = Command::new(bin)
        .args(["report", "--stale", "30d", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    assert!(out.stdout.is_empty(), "stale report on empty root must be empty");
}
