//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: `spool report --stale <duration>` (e.g. `30d`, `7d`) lists skills with zero invocations within the window. Stale skill discovery: comparing skills present in `<root>/skills.txt` (one-line-per-skill, optional) OR all skills ever seen in the journal, vs. those with last_fired older than now-duration.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac6() {
    let root = TempDir::new().unwrap();
    // Manually write a journal file with an old event (1 year ago) for "stale-skill".
    let old_event = serde_json::json!({
        "event": "start",
        "skill": "stale-skill",
        "invocation_id": "01OLD0000000000000000000000",
        "started_at": "2025-05-22T00:00:00Z"
    });
    let mut f = std::fs::File::create(root.path().join("2025-05.jsonl")).unwrap();
    writeln!(f, "{old_event}").unwrap();

    // Fresh event for "active-skill".
    let bin = env!("CARGO_BIN_EXE_spool");
    Command::new(bin)
        .args(["log", "start", "active-skill", "--root"])
        .arg(root.path())
        .output()
        .unwrap();

    let out = Command::new(bin)
        .args(["report", "--stale", "30d", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    assert!(lines.contains(&"stale-skill"), "stale-skill must appear: {stdout}");
    assert!(!lines.contains(&"active-skill"), "active-skill must NOT appear: {stdout}");
}
