//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: Invocation IDs are ULIDs (26 chars, Crockford base32, lexicographically sortable). Two rapid `spool log start` invocations produce two different IDs.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

fn run_start(root: &std::path::Path, skill: &str) -> String {
    let bin = env!("CARGO_BIN_EXE_spool");
    let out = Command::new(bin)
        .args(["log", "start", skill, "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(out.status.success());
    String::from_utf8(out.stdout).unwrap().trim().to_string()
}

#[test]
fn acceptance_ac2() {
    let root = TempDir::new().unwrap();
    let id1 = run_start(root.path(), "skill-a");
    let id2 = run_start(root.path(), "skill-b");

    assert_eq!(id1.len(), 26);
    assert_eq!(id2.len(), 26);
    assert_ne!(id1, id2);
    // Crockford base32 character set: 0-9, A-Z minus I, L, O, U.
    for c in id1.chars().chain(id2.chars()) {
        assert!(c.is_ascii_alphanumeric(), "non-base32 char: {c}");
    }
    // Lexicographically sortable: id2 should be >= id1 (generated later).
    assert!(id2 >= id1, "ULIDs not time-sortable: {id1} {id2}");
}
