//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: `spool rank` reads all `<root>/<YYYY-MM>.jsonl` files, joins start+end pairs by invocation_id, emits a text table sorted by invocation count descending. Columns: skill, invocations, mean_ms, last_fired (RFC3339 or `never`).
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

fn start(root: &std::path::Path, skill: &str) -> String {
    let bin = env!("CARGO_BIN_EXE_spool");
    let out = Command::new(bin)
        .args(["log", "start", skill, "--root"])
        .arg(root)
        .output()
        .unwrap();
    String::from_utf8(out.stdout).unwrap().trim().to_string()
}

#[test]
fn acceptance_ac4() {
    let root = TempDir::new().unwrap();
    let _a = start(root.path(), "self-review");
    let _b = start(root.path(), "self-review");
    let _c = start(root.path(), "update-config");

    let bin = env!("CARGO_BIN_EXE_spool");
    let out = Command::new(bin)
        .args(["rank", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    assert!(lines.len() >= 3, "expected header + 2 skill rows: {stdout}");
    assert!(lines[0].contains("skill"));
    assert!(lines[0].contains("invocations"));
    assert!(lines[0].contains("last_fired"));
    // self-review (2 invocations) should rank above update-config (1).
    let body = lines[1..].join("\n");
    let sr_idx = body.find("self-review").unwrap();
    let uc_idx = body.find("update-config").unwrap();
    assert!(sr_idx < uc_idx, "self-review should be ranked above update-config");
}
