//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: `spool log end <invocation_id> --outcome ok` appends a JSONL line with `event: "end"`, the same `invocation_id`, `ended_at` (RFC3339), `duration_ms` (computed from the matching start event's started_at), and `outcome` ∈ {ok, error, interrupted}.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac3() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_spool");

    // Start.
    let out = Command::new(bin)
        .args(["log", "start", "init", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    let id = String::from_utf8(out.stdout).unwrap().trim().to_string();

    // End.
    let out = Command::new(bin)
        .args(["log", "end", &id, "--outcome", "ok", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));

    // Read journal — last line should be the end event.
    let path = std::fs::read_dir(root.path())
        .unwrap()
        .filter_map(Result::ok)
        .map(|e| e.path())
        .next()
        .unwrap();
    let content = std::fs::read_to_string(path).unwrap();
    let last_line = content.lines().last().unwrap();
    let parsed: serde_json::Value = serde_json::from_str(last_line).unwrap();
    assert_eq!(parsed["event"], "end");
    assert_eq!(parsed["invocation_id"], id);
    assert!(parsed["ended_at"].is_string());
    assert!(parsed["duration_ms"].is_u64(), "duration_ms must be present and numeric");
    assert_eq!(parsed["outcome"], "ok");
}
