//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: `spool rank --format json` emits a JSON array of `{skill, invocations, mean_ms_or_null, last_fired}` objects. Deterministic key ordering; same input always produces byte-identical output.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac5() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_spool");
    // Seed two events.
    Command::new(bin).args(["log", "start", "x", "--root"]).arg(root.path()).output().unwrap();
    Command::new(bin).args(["log", "start", "y", "--root"]).arg(root.path()).output().unwrap();

    let a = Command::new(bin).args(["rank", "--format", "json", "--root"]).arg(root.path()).output().unwrap().stdout;
    let b = Command::new(bin).args(["rank", "--format", "json", "--root"]).arg(root.path()).output().unwrap().stdout;
    assert_eq!(a, b, "deterministic JSON output expected");

    let parsed: serde_json::Value = serde_json::from_slice(&a).unwrap();
    let arr = parsed.as_array().unwrap();
    assert_eq!(arr.len(), 2);
    for entry in arr {
        assert!(entry["skill"].is_string());
        assert!(entry["invocations"].is_u64());
        // mean_ms may be absent (skip_serializing_if Option::is_none).
        assert!(entry["last_fired"].is_string());
    }
}
