//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-telemetry (cli)
//! AC description: `spool log start <skill>` creates (or appends to) `<root>/<YYYY-MM>.jsonl` with one JSONL line containing `event: "start"`, `skill`, `invocation_id` (ULID), `started_at` (RFC3339). Prints just the invocation_id to stdout. `--root <dir>` overrides default `~/.claude/spool/`.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac1() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_spool");
    let out = Command::new(bin)
        .args(["log", "start", "self-review", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let id = String::from_utf8(out.stdout).unwrap().trim().to_string();
    assert_eq!(id.len(), 26, "expected ULID-length id, got: {id}");

    // Find the journal file.
    let entries: Vec<_> = std::fs::read_dir(root.path())
        .unwrap()
        .filter_map(Result::ok)
        .collect();
    assert!(!entries.is_empty(), "no journal file written");
    let path = entries.into_iter().next().unwrap().path();
    let content = std::fs::read_to_string(&path).unwrap();
    let line = content.lines().next().unwrap();
    let parsed: serde_json::Value = serde_json::from_str(line).unwrap();
    assert_eq!(parsed["event"], "start");
    assert_eq!(parsed["skill"], "self-review");
    assert_eq!(parsed["invocation_id"], id);
    assert!(parsed["started_at"].is_string());
}
