//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: tide-chart (cli)
//! AC description: `tide-chart collect --root <dir>` reads ctrace-style ndjson event files under <dir>/events/, aggregates events into hour buckets across the last 24 hours, computes four per-bucket scalars (focus, fragmentation, velocity, surprise) z-scored against a rolling 30-day baseline window, and writes rows into a SQLite database at <dir>/tide.db (table `signals` with columns: bucket_iso, focus, fragmentation, velocity, surprise). Exits 0 on success.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac1() {
    let root = TempDir::new().unwrap();
    let events_dir = root.path().join("events");
    fs::create_dir_all(&events_dir).unwrap();

    // Write a ndjson fixture covering the last few hours plus an older
    // baseline. The collector should bucket the recent events into hour
    // slots and write them to <root>/tide.db.
    let now = chrono::Utc::now();
    let mut lines = Vec::new();
    // Three recent hours, three kinds each.
    for hour_ago in 0..3 {
        let ts = now - chrono::Duration::hours(hour_ago) - chrono::Duration::minutes(1);
        for kind in ["syscall", "exec", "open"] {
            lines.push(format!(
                r#"{{"ts":"{}","kind":"{}"}}"#,
                ts.to_rfc3339(),
                kind
            ));
        }
    }
    // Baseline: a few buckets from 5 days ago.
    for hour_ago in 24..30 {
        let ts = now - chrono::Duration::days(5) - chrono::Duration::hours(hour_ago);
        for kind in ["syscall", "syscall", "open"] {
            lines.push(format!(
                r#"{{"ts":"{}","kind":"{}"}}"#,
                ts.to_rfc3339(),
                kind
            ));
        }
    }
    let fixture = events_dir.join("trace.ndjson");
    fs::write(&fixture, lines.join("\n")).unwrap();

    let bin = env!("CARGO_BIN_EXE_tide-chart");
    let out = Command::new(bin)
        .args(["collect", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(0),
        "collect failed: stdout={} stderr={}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );

    let db_path = root.path().join("tide.db");
    assert!(db_path.exists(), "tide.db not created at {}", db_path.display());

    // Open the DB and check the signals table has the expected columns + rows.
    let conn = rusqlite::Connection::open(&db_path).unwrap();
    // Schema check: pragma table_info(signals) lists columns.
    let cols: Vec<String> = conn
        .prepare("PRAGMA table_info(signals)")
        .unwrap()
        .query_map([], |r| r.get::<_, String>(1))
        .unwrap()
        .filter_map(Result::ok)
        .collect();
    for col in ["bucket_iso", "focus", "fragmentation", "velocity", "surprise"] {
        assert!(
            cols.iter().any(|c| c == col),
            "missing column {col} in signals (have: {cols:?})"
        );
    }
    // Row count > 0.
    let n: i64 = conn
        .query_row("SELECT COUNT(*) FROM signals", [], |r| r.get(0))
        .unwrap();
    assert!(n > 0, "no rows written to signals (n={n})");
}
