//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: tide-chart (cli)
//! AC description: Calling `tide-chart chart` against a `--root` directory that has no `tide.db` exits non-zero with stderr message containing both the missing path and the suggestion `run collect first`.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac3() {
    let root = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_tide-chart");
    let out = Command::new(bin)
        .args(["chart", "--today", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_ne!(out.status.code(), Some(0), "expected non-zero exit on missing tide.db");

    let stderr = String::from_utf8_lossy(&out.stderr);
    let missing_path = root.path().join("tide.db");
    assert!(
        stderr.contains(&missing_path.display().to_string()),
        "stderr should mention missing path {}, got: {stderr}",
        missing_path.display()
    );
    assert!(
        stderr.contains("run collect first"),
        "stderr should suggest 'run collect first', got: {stderr}"
    );
}
