//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: tide-chart (cli)
//! AC description: `tide-chart collect` is idempotent over the same input events: running it twice produces identical rows in `signals` (no duplicates, no drift). The collector uses a stable INSERT OR REPLACE keyed on bucket_iso.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

fn dump_signals(db: &std::path::Path) -> Vec<(String, f64, f64, f64, f64)> {
    let conn = rusqlite::Connection::open(db).unwrap();
    let mut stmt = conn
        .prepare("SELECT bucket_iso, focus, fragmentation, velocity, surprise FROM signals ORDER BY bucket_iso ASC")
        .unwrap();
    stmt.query_map([], |r| {
        Ok((
            r.get::<_, String>(0)?,
            r.get::<_, f64>(1)?,
            r.get::<_, f64>(2)?,
            r.get::<_, f64>(3)?,
            r.get::<_, f64>(4)?,
        ))
    })
    .unwrap()
    .filter_map(Result::ok)
    .collect()
}

#[test]
fn acceptance_ac5() {
    let root = TempDir::new().unwrap();
    let events_dir = root.path().join("events");
    fs::create_dir_all(&events_dir).unwrap();

    let now = chrono::Utc::now();
    let mut lines = Vec::new();
    for hour_ago in 0..6 {
        let ts = now - chrono::Duration::hours(hour_ago) - chrono::Duration::minutes(3);
        for kind in ["a", "b", "c", "a", "a"] {
            lines.push(format!(
                r#"{{"ts":"{}","kind":"{}"}}"#,
                ts.to_rfc3339(),
                kind
            ));
        }
    }
    fs::write(events_dir.join("trace.ndjson"), lines.join("\n")).unwrap();

    let bin = env!("CARGO_BIN_EXE_tide-chart");

    let out1 = Command::new(bin).args(["collect", "--root"]).arg(root.path()).output().unwrap();
    assert_eq!(out1.status.code(), Some(0));
    let dump1 = dump_signals(&root.path().join("tide.db"));

    let out2 = Command::new(bin).args(["collect", "--root"]).arg(root.path()).output().unwrap();
    assert_eq!(out2.status.code(), Some(0));
    let dump2 = dump_signals(&root.path().join("tide.db"));

    assert_eq!(dump1.len(), dump2.len(), "row count drifted: {} -> {}", dump1.len(), dump2.len());
    assert_eq!(dump1, dump2, "row values drifted between idempotent runs");
}
