//! Acceptance test for AC6 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: tide-chart (cli)
//! AC description: `tide-chart chart --7day --root <dir>` prints a 7-day strip: one row per signal, each row 7 cells wide where each cell is the day's mean of that signal.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac6() {
    let root = TempDir::new().unwrap();
    let events_dir = root.path().join("events");
    fs::create_dir_all(&events_dir).unwrap();

    // Spread events over many of the last 24 hours so the 7-day view has at
    // least one populated day cell.
    let now = chrono::Utc::now();
    let mut lines = Vec::new();
    for hour_ago in 0..24 {
        let ts = now - chrono::Duration::hours(hour_ago) - chrono::Duration::minutes(5);
        for kind in ["syscall", "exec", "open"] {
            lines.push(format!(
                r#"{{"ts":"{}","kind":"{}"}}"#,
                ts.to_rfc3339(),
                kind
            ));
        }
    }
    fs::write(events_dir.join("trace.ndjson"), lines.join("\n")).unwrap();

    let bin = env!("CARGO_BIN_EXE_tide-chart");
    let collect = Command::new(bin)
        .args(["collect", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(collect.status.code(), Some(0));

    let chart = Command::new(bin)
        .args(["chart", "--7day", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(
        chart.status.code(),
        Some(0),
        "chart --7day failed: stderr={}",
        String::from_utf8_lossy(&chart.stderr)
    );

    let out = String::from_utf8(chart.stdout).unwrap();
    let lines: Vec<&str> = out.lines().collect();
    assert_eq!(lines.len(), 4, "expected 4 rows, got {}: {out:?}", lines.len());

    let allowed = ['\u{2581}', '\u{2582}', '\u{2583}', '\u{2584}', '\u{2585}', '\u{2586}', '\u{2587}', '\u{2588}'];
    let expected_labels = ["focus", "frag", "velocity", "surprise"];
    for (i, line) in lines.iter().enumerate() {
        let label_field: String = line.chars().take(8).collect();
        assert_eq!(label_field, format!("{:>8}", expected_labels[i]), "row {i} label");
        let cells: Vec<char> = line.chars().skip(9).collect();
        assert_eq!(cells.len(), 7, "row {i} should have 7 cells, got {}: {line:?}", cells.len());
        for c in &cells {
            assert!(
                allowed.contains(c) || *c == '.' || *c == '+' || *c == '*' || *c == '#',
                "row {i} has non-allowed glyph {c:?}"
            );
        }
    }
}
