//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: tide-chart (cli)
//! AC description: `tide-chart chart --today --root <dir>` reads `<dir>/tide.db` and prints a 4-line ASCII chart for the last 24 hours to stdout: one line per signal, each line 24 columns wide, using one of `▁▂▃▄▅▆▇█` or `.+*#` characters to encode normalized intensity. Each line is prefixed with the signal name (8 chars, left-padded). Exits 0 on success.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac2() {
    let root = TempDir::new().unwrap();
    let events_dir = root.path().join("events");
    fs::create_dir_all(&events_dir).unwrap();

    // Fixture spanning many of the last 24 hours so chart has data to bin.
    let now = chrono::Utc::now();
    let mut lines = Vec::new();
    for hour_ago in 0..24 {
        let ts = now - chrono::Duration::hours(hour_ago) - chrono::Duration::minutes(5);
        for kind in ["syscall", "exec", "open", "close"] {
            lines.push(format!(
                r#"{{"ts":"{}","kind":"{}"}}"#,
                ts.to_rfc3339(),
                kind
            ));
        }
    }
    fs::write(events_dir.join("trace.ndjson"), lines.join("\n")).unwrap();

    let bin = env!("CARGO_BIN_EXE_tide-chart");
    let collect = Command::new(bin)
        .args(["collect", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(collect.status.code(), Some(0), "collect failed: {}", String::from_utf8_lossy(&collect.stderr));

    let chart = Command::new(bin)
        .args(["chart", "--today", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(
        chart.status.code(),
        Some(0),
        "chart failed: stdout={} stderr={}",
        String::from_utf8_lossy(&chart.stdout),
        String::from_utf8_lossy(&chart.stderr)
    );

    let out = String::from_utf8(chart.stdout).unwrap();
    let lines: Vec<&str> = out.lines().collect();
    assert_eq!(lines.len(), 4, "expected 4 lines, got {}: {out:?}", lines.len());

    // Allowed glyphs for the intensity cells.
    let allowed = ['\u{2581}', '\u{2582}', '\u{2583}', '\u{2584}', '\u{2585}', '\u{2586}', '\u{2587}', '\u{2588}'];

    let expected_labels = ["focus", "frag", "velocity", "surprise"];
    for (i, line) in lines.iter().enumerate() {
        let label_field: String = line.chars().take(8).collect();
        let expected = format!("{:>8}", expected_labels[i]);
        assert_eq!(label_field, expected, "row {i} label mismatch: {line:?}");
        // After label + single space, 24 cells follow.
        let after: String = line.chars().skip(9).collect();
        let cells: Vec<char> = after.chars().collect();
        assert_eq!(cells.len(), 24, "row {i} should have 24 cells, got {}: {after:?}", cells.len());
        for c in &cells {
            assert!(
                allowed.contains(c) || *c == '.' || *c == '+' || *c == '*' || *c == '#',
                "row {i} has non-allowed glyph {c:?}"
            );
        }
    }
}
