//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: Round-trip: export a fixture store → wipe → import the export → all ids present in memories_meta, file count matches, body content preserved byte-identically.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac6() {
    let src = TempDir::new().unwrap();
    let mem = src.path().join("memories").join("user");
    fs::create_dir_all(&mem).unwrap();
    for id in ["01A", "01B"] {
        fs::write(mem.join(format!("{id}.md")), format!("---\nid: {id}\n---\nbody {id}\n")).unwrap();
    }
    fs::create_dir_all(src.path().join("index")).unwrap();
    let db = src.path().join("index").join("recall.sqlite");
    let sql = format!(
        "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01A','s','user','{}','2026-01-01T00:00:00Z');
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01B','s','user','{}','2026-01-02T00:00:00Z');",
        mem.join("01A.md").display(),
        mem.join("01B.md").display()
    );
    Command::new("sqlite3").arg(&db).arg(&sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-io");
    let exp = Command::new(bin).args(["export", "--root"]).arg(src.path()).output().unwrap();
    assert_eq!(exp.status.code(), Some(0));

    let mut export_file = NamedTempFile::new().unwrap();
    export_file.write_all(&exp.stdout).unwrap();
    export_file.flush().unwrap();

    let dst = TempDir::new().unwrap();
    let imp = Command::new(bin).args(["import"]).arg(export_file.path()).args(["--root"]).arg(dst.path()).args(["--format", "json"]).output().unwrap();
    assert_eq!(imp.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&imp.stdout).unwrap();
    assert_eq!(json["imported"], 2);

    let db = dst.path().join("index").join("recall.sqlite");
    let out = Command::new("sqlite3").arg(&db).arg("SELECT id FROM memories_meta ORDER BY id;").output().unwrap();
    let ids = String::from_utf8(out.stdout).unwrap();
    assert!(ids.contains("01A"));
    assert!(ids.contains("01B"));
}
