//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: `--replace` flag overrides skip behavior: duplicate ids cause the existing .md + index row to be replaced with the imported version.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac5() {
    let dest = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-io");

    let mut f1 = NamedTempFile::new().unwrap();
    writeln!(f1, r#"{{"id":"01R","kind":"s","subject":"user","path":"/x","created_at":"2026-01-01T00:00:00Z","body":"original"}}"#).unwrap();
    f1.flush().unwrap();
    Command::new(bin).args(["import"]).arg(f1.path()).args(["--root"]).arg(dest.path()).output().unwrap();

    let mut f2 = NamedTempFile::new().unwrap();
    writeln!(f2, r#"{{"id":"01R","kind":"s","subject":"user","path":"/x","created_at":"2026-01-01T00:00:00Z","body":"replaced"}}"#).unwrap();
    f2.flush().unwrap();
    let out = Command::new(bin).args(["import"]).arg(f2.path()).args(["--root"]).arg(dest.path()).arg("--replace").args(["--format", "json"]).output().unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["imported"], 1);

    let written = dest.path().join("memories").join("user").join("01R.md");
    let content = fs::read_to_string(&written).unwrap();
    assert!(content.contains("replaced"));
    assert!(!content.contains("original"));
}
