//! Acceptance test for AC9 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: `--format json` for import emits a single summary JSON object to stdout; text mode emits a one-line summary plus per-line warnings to stderr.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac9() {
    let mut f = NamedTempFile::new().unwrap();
    writeln!(f, r#"{{"id":"01J","kind":"s","subject":"user","path":"/x","created_at":"2026-01-01T00:00:00Z","body":"ok"}}"#).unwrap();
    f.flush().unwrap();
    let dest = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-io");

    let out = Command::new(bin).args(["import"]).arg(f.path()).args(["--root"]).arg(dest.path()).args(["--format", "json"]).output().unwrap();
    let stdout = String::from_utf8(out.stdout).unwrap();
    let _: serde_json::Value = serde_json::from_str(stdout.trim()).unwrap();

    let dest2 = TempDir::new().unwrap();
    let out = Command::new(bin).args(["import"]).arg(f.path()).args(["--root"]).arg(dest2.path()).output().unwrap();
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert!(stdout.contains("imported=1"));
}
