//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: Export is deterministic: sorted by id ascending. Two consecutive exports of the same store produce byte-identical output.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac2() {
    let root = TempDir::new().unwrap();
    let mem = root.path().join("memories").join("user");
    fs::create_dir_all(&mem).unwrap();
    for id in ["01C", "01A", "01B"] {
        fs::write(mem.join(format!("{id}.md")), format!("---\nid: {id}\n---\nbody {id}\n")).unwrap();
    }
    fs::create_dir_all(root.path().join("index")).unwrap();
    let db = root.path().join("index").join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01C','s','user','/c','2026-01-01T00:00:00Z');
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01A','s','user','/a','2026-01-01T00:00:00Z');
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01B','s','user','/b','2026-01-01T00:00:00Z');";
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-io");
    let run = || Command::new(bin).args(["export", "--root"]).arg(root.path()).output().unwrap().stdout;
    let a = run();
    let b = run();
    assert_eq!(a, b, "export must be byte-identical across runs");

    let stdout = String::from_utf8(a).unwrap();
    let ids: Vec<&str> = stdout
        .lines()
        .map(|l| {
            if l.contains("\"id\":\"01A\"") { "01A" }
            else if l.contains("\"id\":\"01B\"") { "01B" }
            else { "01C" }
        })
        .collect();
    assert_eq!(ids, vec!["01A", "01B", "01C"], "export must be sorted by id");
}
