//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: `recall-io import` from stdin works: `--` as the filename reads from stdin. Useful for shell pipes (e.g. `recall-io export --root A | recall-io import - --root B`).
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::{Command, Stdio};
use tempfile::TempDir;

#[test]
fn acceptance_ac10() {
    let dest = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-io");
    let record = r#"{"id":"01S","kind":"s","subject":"user","path":"/x","created_at":"2026-01-01T00:00:00Z","body":"from stdin"}"#;
    let mut child = Command::new(bin)
        .args(["import", "-", "--root"])
        .arg(dest.path())
        .args(["--format", "json"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.as_mut().unwrap().write_all(format!("{record}\n").as_bytes()).unwrap();
    drop(child.stdin.take());
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["imported"], 1);
}
