//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: Malformed JSON lines on import → log to stderr with line number, count in `errors`, continue. Lines missing required fields (id, kind, subject) → same treatment.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac7() {
    let mut f = NamedTempFile::new().unwrap();
    writeln!(f, r#"{{"id":"01OK","kind":"s","subject":"user","path":"/x","created_at":"2026-01-01T00:00:00Z","body":"ok"}}"#).unwrap();
    writeln!(f, "this is not json").unwrap();
    writeln!(f, r#"{{"path":"/y"}}"#).unwrap();
    f.flush().unwrap();

    let dest = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-io");
    let out = Command::new(bin).args(["import"]).arg(f.path()).args(["--root"]).arg(dest.path()).args(["--format", "json"]).output().unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["imported"], 1);
    assert!(json["errors"].as_u64().unwrap() >= 2);
}
