//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: `recall-io export [--root <dir>]` emits one JSON object per memory to stdout (NDJSON, one per line). Each object contains: `id`, `kind`, `subject`, `path`, `confidence`, `created_at`, `last_recalled_at`, `recall_count`, `embedding_id`, `supersedes_json`, plus the `body` (from the .md file, post-frontmatter). Empty store → empty output, exit 0.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

fn seed_one(root: &std::path::Path) {
    fs::create_dir_all(root.join("memories").join("user")).unwrap();
    fs::write(
        root.join("memories").join("user").join("01A.md"),
        "---\nid: 01A\n---\nbody one\n",
    )
    .unwrap();
    fs::create_dir_all(root.join("index")).unwrap();
    let db = root.join("index").join("recall.sqlite");
    let path_str = root.join("memories").join("user").join("01A.md").to_string_lossy().to_string();
    let sql = format!(
        "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01A','semantic','user','{path_str}','2026-01-01T00:00:00Z');"
    );
    Command::new("sqlite3").arg(&db).arg(&sql).output().unwrap();
}

#[test]
fn acceptance_ac1() {
    let root = TempDir::new().unwrap();
    seed_one(root.path());
    let bin = env!("CARGO_BIN_EXE_recall-io");
    let out = Command::new(bin).args(["export", "--root"]).arg(root.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    assert_eq!(lines.len(), 1, "expected 1 line, got: {stdout}");
    let json: serde_json::Value = serde_json::from_str(lines[0]).unwrap();
    for k in ["id", "kind", "subject", "path", "created_at", "body"] {
        assert!(json.get(k).is_some(), "missing key {k}");
    }
    assert_eq!(json["id"], "01A");
    assert!(json["body"].as_str().unwrap().contains("body one"));
}
