//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: Exit codes: 0 = success; 1 = expected failure (no candidates exported on empty store with --strict; all import lines invalid); 2 = invocation error (bad path, sqlite3 unavailable, --root that's not a dir).
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac8() {
    let bin = env!("CARGO_BIN_EXE_recall-io");

    let root = TempDir::new().unwrap();
    let out = Command::new(bin).args(["export", "--root"]).arg(root.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));

    let mut f = NamedTempFile::new().unwrap();
    writeln!(f, "garbage").unwrap();
    writeln!(f, "more garbage").unwrap();
    f.flush().unwrap();
    let dest = TempDir::new().unwrap();
    let out = Command::new(bin).args(["import"]).arg(f.path()).args(["--root"]).arg(dest.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(1));

    let not_dir = NamedTempFile::new().unwrap();
    let out = Command::new(bin).args(["export", "--root"]).arg(not_dir.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(2));

    let out = Command::new(bin).args(["import", "/no/such/path/here.jsonl"]).output().unwrap();
    assert_eq!(out.status.code(), Some(2));
}
