//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: Import is additive by default — duplicate ids (already present in memories_meta) are SKIPPED with a stderr warning, original row + file untouched. Reports `{imported: N, skipped: M, errors: K}` in JSON mode.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac4() {
    let mut f = NamedTempFile::new().unwrap();
    let rec = r#"{"id":"01D","kind":"s","subject":"user","path":"/x","created_at":"2026-01-01T00:00:00Z","body":"v1"}"#;
    writeln!(f, "{rec}").unwrap();
    f.flush().unwrap();

    let dest = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-io");

    let out = Command::new(bin).args(["import"]).arg(f.path()).args(["--root"]).arg(dest.path()).args(["--format", "json"]).output().unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["imported"], 1);

    let out = Command::new(bin).args(["import"]).arg(f.path()).args(["--root"]).arg(dest.path()).args(["--format", "json"]).output().unwrap();
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["imported"], 0);
    assert_eq!(json["skipped"], 1);
}
