//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-io (cli)
//! AC description: `recall-io import <jsonl-path>` reads the NDJSON stream, writes one .md file per memory to `<root>/memories/<subject>/<id>.md` (with frontmatter + body), and INSERTs rows into memories_meta. Creates the root dir + index if absent.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac3() {
    let mut f = NamedTempFile::new().unwrap();
    let record = r#"{"id":"01X","kind":"semantic","subject":"user","path":"/tmp/x","created_at":"2026-01-01T00:00:00Z","body":"imported body"}"#;
    writeln!(f, "{record}").unwrap();
    f.flush().unwrap();

    let dest = TempDir::new().unwrap();
    let bin = env!("CARGO_BIN_EXE_recall-io");
    let out = Command::new(bin).args(["import"]).arg(f.path()).args(["--root"]).arg(dest.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));

    let written = dest.path().join("memories").join("user").join("01X.md");
    assert!(written.exists(), "imported .md must exist at {}", written.display());
    let content = fs::read_to_string(&written).unwrap();
    assert!(content.contains("imported body"));
    assert!(content.contains("id: 01X"));

    let db = dest.path().join("index").join("recall.sqlite");
    let out = Command::new("sqlite3").arg(&db).arg("SELECT id FROM memories_meta WHERE id='01X';").output().unwrap();
    assert_eq!(String::from_utf8(out.stdout).unwrap().trim(), "01X");
}
