//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: The `revert` detector fires when an Edit or Write tool-use is followed within 5 turns by another Edit/Write that returns the same path's content to its pre-change state (textual revert). Produces a candidate with `detector: "revert"`, both turn indices in evidence, and the path that was reverted.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const REVERT_FIXTURE: &str = r#"{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/foo.rs","old_string":"X","new_string":"Y"}}}
{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/foo.rs","old_string":"Y","new_string":"X"}}}
"#;

#[test]
fn acceptance_ac5() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(REVERT_FIXTURE.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_episode");
    let out = Command::new(bin)
        .args(["observe", "--dry-run"])
        .arg(f.path())
        .output()
        .unwrap();
    let arr: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let cand = arr
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["detector"] == "revert")
        .unwrap();
    let ev = cand["evidence"].as_array().unwrap();
    assert_eq!(ev.len(), 2);
    assert!(ev[0]["excerpt"].as_str().unwrap().contains("/foo.rs"));
    assert!(cand["body"].as_str().unwrap().contains("/foo.rs"));
}
