//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: `--max-memories <N>` caps the total number of emitted candidates across all detectors. Default cap is 5. When the cap is reached the CLI stops emitting and exits 0; surplus matches are dropped silently.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

#[test]
fn acceptance_ac7() {
    // Build a fixture with 3 user-redirects (would emit 3 candidates).
    let mut content = String::new();
    for _ in 0..3 {
        content.push_str(r#"{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/x"}}}"#);
        content.push('\n');
        content.push_str(r#"{"type":"user","text":"no, change something"}"#);
        content.push('\n');
    }
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(content.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_episode");

    // Default cap (5): should emit all 3.
    let out = Command::new(bin)
        .args(["observe", "--dry-run"])
        .arg(f.path())
        .output()
        .unwrap();
    let arr: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(arr.as_array().unwrap().len(), 3);

    // Cap at 2: should emit only 2.
    let out = Command::new(bin)
        .args(["observe", "--dry-run", "--max-memories", "2"])
        .arg(f.path())
        .output()
        .unwrap();
    let arr: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(arr.as_array().unwrap().len(), 2);
}
