//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: The `user-redirect` detector fires when a user-role message starts with a redirect keyword (one of: `no`, `stop`, `don't`, `dont`, `actually`, `wait`) within 2 turns of an assistant-role tool-use. Produces a candidate with `detector: "user-redirect"`, the literal quote as `excerpt`, and the turn index.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

fn run_dry(content: &str) -> Vec<serde_json::Value> {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(content.as_bytes()).unwrap();
    f.flush().unwrap();
    let bin = env!("CARGO_BIN_EXE_episode");
    let out = Command::new(bin)
        .args(["observe", "--dry-run"])
        .arg(f.path())
        .output()
        .unwrap();
    let stdout = String::from_utf8(out.stdout).unwrap();
    let v: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    v.as_array().unwrap().clone()
}

#[test]
fn acceptance_ac4() {
    // Fires: tool-use then user-redirect.
    let fixture = r#"{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/x"}}}
{"type":"user","text":"no, do something else"}
"#;
    let arr = run_dry(fixture);
    let cand = arr.iter().find(|c| c["detector"] == "user-redirect").unwrap();
    let ev = cand["evidence"].as_array().unwrap();
    let user_ev = ev.iter().find(|e| e["excerpt"].as_str().is_some_and(|s| s.starts_with("no,"))).unwrap();
    assert_eq!(user_ev["excerpt"], "no, do something else");
    assert!(user_ev["turn"].is_u64());

    // Doesn't fire: user message starts with non-redirect word.
    let fixture = r#"{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/x"}}}
{"type":"user","text":"sure, looks good"}
"#;
    let arr = run_dry(fixture);
    assert!(arr.iter().all(|c| c["detector"] != "user-redirect"));
}
