//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: The `retry-with-tweak` detector fires when a Bash tool-use exits non-zero, followed within 3 turns by another Bash tool-use with a similar command (Jaccard token similarity ≥ 0.5 ignoring whitespace) that exits zero. Produces a candidate with `detector: "retry-with-tweak"`, both commands as evidence excerpts.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const RETRY: &str = r#"{"type":"assistant","tool_use":{"name":"Bash","input":{"command":"cargo test foo"}}}
{"type":"tool_result","for_turn":1,"exit_code":1,"is_error":true}
{"type":"assistant","tool_use":{"name":"Bash","input":{"command":"cargo test foo --release"}}}
{"type":"tool_result","for_turn":3,"exit_code":0,"is_error":false}
"#;

#[test]
fn acceptance_ac6() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(RETRY.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_episode");
    let out = Command::new(bin)
        .args(["observe", "--dry-run"])
        .arg(f.path())
        .output()
        .unwrap();
    let arr: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let cand = arr
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["detector"] == "retry-with-tweak")
        .unwrap();
    let ev = cand["evidence"].as_array().unwrap();
    assert_eq!(ev.len(), 2);
    assert!(ev[0]["excerpt"].as_str().unwrap().contains("cargo test foo"));
    assert!(ev[1]["excerpt"].as_str().unwrap().contains("--release"));
}
