//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: `episode observe --dry-run <jsonl-path>` emits a JSON array of candidate memories to stdout, each with `{detector, subject, body, evidence: [{session, turn, excerpt}]}`. Without `--dry-run` the CLI emits nothing on stdout (writing is downstream).
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

// A session with one user-redirect (assistant tool-use, then user "no").
const REDIRECT: &str = r#"{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/x"}}}
{"type":"user","text":"no, that path is wrong"}
"#;

#[test]
fn acceptance_ac2() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(REDIRECT.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_episode");
    let out = Command::new(bin)
        .args(["observe", "--dry-run"])
        .arg(f.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let arr: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    let arr = arr.as_array().unwrap();
    assert!(!arr.is_empty(), "expected at least one candidate from REDIRECT fixture");
    let c = &arr[0];
    for k in ["detector", "subject", "body", "evidence"] {
        assert!(c.get(k).is_some(), "candidate missing key {k}: {c}");
    }
    let ev = c["evidence"].as_array().unwrap();
    for e in ev {
        for k in ["session", "turn", "excerpt"] {
            assert!(e.get(k).is_some(), "evidence entry missing {k}: {e}");
        }
    }
}
