//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: CLI binary `episode` accepts subcommand `observe <jsonl-path>` and parses a fixture JSONL stream of session events without panicking. Exit 0 when the fixture has no detector matches; emit nothing to stdout.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const QUIET: &str = r#"{"type":"user","text":"hello"}
{"type":"assistant","tool_use":{"name":"Read","input":{"path":"/x"}}}
"#;

#[test]
fn acceptance_ac1() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(QUIET.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_episode");
    let out = Command::new(bin).arg("observe").arg(f.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    assert!(out.stdout.is_empty(), "stdout must be empty without --dry-run");
}
