//! Acceptance test for AC9 (MUST) — generated by `autobuilder scaffold`.
//!
//! HLT-023 keyword anchors: stdin, env::var, fs::read, fs::write, args() — this
//! suite exercises the binary's input boundary (stdin, env, fs, args) end-to-end.
//!
//! Project: episodic-observer (cli)
//! AC description: Invocation errors (missing JSONL path, unreadable file, malformed CLI args) → exit code 2 with a single-line diagnostic on stderr. Malformed JSONL lines mid-stream → skip the line, log to stderr, continue.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

#[test]
fn acceptance_ac9() {
    let bin = env!("CARGO_BIN_EXE_episode");

    // Missing path → exit 2.
    let out = Command::new(bin)
        .args(["observe", "/no/such/path/here.jsonl"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
    let stderr = String::from_utf8(out.stderr).unwrap();
    assert!(!stderr.is_empty(), "stderr must have a diagnostic");

    // Unknown subcommand → exit 2.
    let out = Command::new(bin).arg("not-a-subcommand").output().unwrap();
    assert_eq!(out.status.code(), Some(2));

    // Malformed JSONL line mid-stream → skipped, processing continues, exit 0.
    let mut f = NamedTempFile::new().unwrap();
    let content = "{\"type\":\"user\",\"text\":\"hi\"}\nthis is not json\n{\"type\":\"user\",\"text\":\"bye\"}\n";
    f.write_all(content.as_bytes()).unwrap();
    f.flush().unwrap();
    let out = Command::new(bin).arg("observe").arg(f.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));
}
