//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: `episode detectors` lists the available detector names to stdout, one per line. At minimum: `revert`, `user-redirect`, `retry-with-tweak`. Exit 0.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

#[test]
fn acceptance_ac3() {
    let bin = env!("CARGO_BIN_EXE_episode");
    let out = Command::new(bin).arg("detectors").output().unwrap();
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let lines: Vec<&str> = stdout.lines().collect();
    for required in ["revert", "user-redirect", "retry-with-tweak"] {
        assert!(lines.contains(&required), "missing detector: {required}");
    }
}
