//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: Idempotency: running `episode observe --dry-run <fixture>` twice produces byte-identical stdout. Ordering of candidates is deterministic (sorted by detector name, then turn index).
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const MIXED: &str = r#"{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/foo.rs","old_string":"X","new_string":"Y"}}}
{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/foo.rs","old_string":"Y","new_string":"X"}}}
{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/x"}}}
{"type":"user","text":"no, change something"}
"#;

#[test]
fn acceptance_ac10() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(MIXED.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_episode");
    let run = || {
        Command::new(bin)
            .args(["observe", "--dry-run"])
            .arg(f.path())
            .output()
            .unwrap()
            .stdout
    };
    let a = run();
    let b = run();
    assert_eq!(a, b, "two runs must be byte-identical");

    // Ordering: sorted by detector name. "retry-with-tweak", "revert", "user-redirect" alphabetically.
    let arr: serde_json::Value = serde_json::from_slice(&a).unwrap();
    let names: Vec<&str> = arr
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c["detector"].as_str().unwrap())
        .collect();
    // The fixture has 1 revert and 1 user-redirect — no retry. Should be ["revert","user-redirect"].
    assert_eq!(names, vec!["revert", "user-redirect"]);
}
