//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: episodic-observer (cli)
//! AC description: Each emitted candidate's `subject` field is derived as `project:<basename of cwd>` when run from a project dir, falling back to `project:unknown` when cwd is `/` or unset. Subject is included in JSON output and is deterministic per-fixture.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::{NamedTempFile, TempDir};

#[test]
fn acceptance_ac8() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(
        r#"{"type":"assistant","tool_use":{"name":"Edit","input":{"path":"/x"}}}
{"type":"user","text":"no, stop"}
"#
        .as_bytes(),
    )
    .unwrap();
    f.flush().unwrap();
    let jsonl_path = f.path().to_owned();

    // Run from a cwd named "the-test-project".
    let parent = TempDir::new().unwrap();
    let cwd = parent.path().join("the-test-project");
    std::fs::create_dir_all(&cwd).unwrap();

    let bin = env!("CARGO_BIN_EXE_episode");
    let out = Command::new(bin)
        .current_dir(&cwd)
        .args(["observe", "--dry-run"])
        .arg(&jsonl_path)
        .output()
        .unwrap();
    let arr: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let cand = &arr.as_array().unwrap()[0];
    assert_eq!(cand["subject"], "project:the-test-project");
}
