//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: `morsel-bake --in <safetensors-file> --arch <name> --out <rust-file>` reads tensors from the safetensors file, emits Rust source containing one `pub const NAME: [[f32; N]; M] = ...;` (or 1-D `[f32; N]`) per tensor, plus `pub const ARCH_FINGERPRINT: &str = "<arch>-<dim-summary>-v1";`. Exit 0 on success.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac1() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC1 not yet implemented — see file header");
}
