//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Const arrays preserve f32 precision exactly — round-tripping (write tensor → safetensors → bake → const → parse from emitted source) yields bit-identical f32 bytes. Use Rust's `{:e}` or `f32::from_bits` style if needed to avoid lossy formatting.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac2() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC2 not yet implemented — see file header");
}
