//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Tensors with rank > 2 are emitted as Rust nested arrays one dimension deeper per rank (`[[[f32; D2]; D1]; D0]`). Rank-0 (scalar) tensors emit `pub const NAME: f32 = ...;`. Rank > 4 → exit 6 with stderr `rank N exceeds supported max 4`.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac6() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC6 not yet implemented — see file header");
}
