//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel-bake (cli)
//! AC description: Tensors with dtype other than f32 → exit 5 with stderr listing the offending tensor and its dtype, and the message `only f32 supported in Phase 0a`. (f16/bf16/int8 are Phase 0b with --quant flag.)
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac5() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC5 not yet implemented — see file header");
}
