//! Acceptance test for AC8 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: letters-we-never-sent (cli)
//! AC description: `letter open <filename> [--root <dir>]` invokes $EDITOR on the file (so the user can edit in-place during a curation session). Exit 0 if editor exits 0.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

#[test]
fn acceptance_ac8() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    let path = root.join("01.md");
    std::fs::write(&path, "---\nstate: pending\n---\nbody\n").unwrap();

    // Use POSIX `true` as the editor — exits 0 without touching the file.
    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .env("EDITOR", "true")
        .args(["open", "01.md", "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(out.status.success(), "open with EDITOR=true failed: {out:?}");
    assert_eq!(out.status.code(), Some(0));

    // Non-zero editor exit propagates.
    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .env("EDITOR", "false")
        .args(["open", "01.md", "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(!out.status.success(), "open should propagate non-zero from editor");

    // Missing file errors.
    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .env("EDITOR", "true")
        .args(["open", "missing.md", "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(!out.status.success(), "missing file should error");
}
