//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: letters-we-never-sent (cli)
//! AC description: Filenames are positional arguments; both relative-to-root (`NN.md`) and absolute paths are accepted. Glob patterns (e.g. `2026-05-*.md`) are NOT auto-expanded — the user uses shell globbing for that. Single filename per invocation.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

#[test]
fn acceptance_ac6() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    let path = root.join("01.md");
    std::fs::write(&path, "---\nstate: pending\n---\nbody\n").unwrap();

    // Relative path resolves against --root.
    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .args(["accept", "01.md", "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(out.status.success(), "relative path failed: {out:?}");
    assert!(std::fs::read_to_string(&path).unwrap().contains("state: accepted"));

    // Reset.
    std::fs::write(&path, "---\nstate: pending\n---\nbody\n").unwrap();

    // Absolute path works without --root.
    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .arg("decline")
        .arg(&path)
        .output()
        .unwrap();
    assert!(out.status.success(), "absolute path failed: {out:?}");
    assert!(std::fs::read_to_string(&path).unwrap().contains("state: declined"));

    // Glob argument is NOT auto-expanded — it's passed through as a literal
    // filename and the file does not exist, so the command must error
    // (NOT silently match 01.md).
    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .args(["accept", "*.md", "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(!out.status.success(), "glob silently matched: {out:?}");

    // Multiple positional filenames are rejected by clap.
    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .args(["accept", "01.md", "02.md", "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(!out.status.success(), "multiple filenames accepted: {out:?}");
}
