//! Acceptance test for AC7 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: letters-we-never-sent (cli)
//! AC description: `letter stats [--root <dir>] [--year <YYYY>]` prints aggregate counts to stdout: `accepted: N, declined: N, pending: N, send-real: N, total: N`. Multi-line, machine-grep-able.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

#[test]
fn acceptance_ac7() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    let yr = root.join("2026");
    std::fs::create_dir_all(&yr).unwrap();
    let mk = |name: &str, state: &str| {
        std::fs::write(
            yr.join(name),
            format!("---\nmonth: 2026-05\nstate: {state}\n---\nbody\n"),
        )
        .unwrap();
    };
    mk("a.md", "accepted");
    mk("b.md", "accepted");
    mk("c.md", "declined");
    mk("d.md", "pending");
    mk("e.md", "send-real");

    let out = Command::new(env!("CARGO_BIN_EXE_letter"))
        .args(["stats", "--year", "2026", "--root"])
        .arg(root)
        .output()
        .unwrap();
    assert!(out.status.success(), "stats failed: {out:?}");
    let stdout = String::from_utf8(out.stdout).unwrap();
    // Multi-line, machine-grep-able lines.
    assert!(stdout.contains("accepted: 2"), "accepted count wrong: {stdout:?}");
    assert!(stdout.contains("declined: 1"), "declined count wrong: {stdout:?}");
    assert!(stdout.contains("pending: 1"), "pending count wrong: {stdout:?}");
    assert!(stdout.contains("send-real: 1"), "send-real count wrong: {stdout:?}");
    assert!(stdout.contains("total: 5"), "total wrong: {stdout:?}");
    // Each on its own line.
    assert!(stdout.lines().count() >= 5, "expected >=5 lines: {stdout:?}");
}
