//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `recall-ops lineage <id> [--format text|json]` walks `supersedes_json` (a JSON array of ids stored on each row) bidirectionally: ancestors (this row supersedes …) and descendants (this row is superseded by …). Returns chain entries with id, kind, subject, created_at. 1-deep chain returns 1 entry; cycles are broken at first repeat.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac6() {
    let root = TempDir::new().unwrap();
    fs::create_dir_all(root.path().join("index")).unwrap();
    let db = root.path().join("index").join("recall.sqlite");
    // Chain: 01ROOT supersedes [01ANC]; 01NEW supersedes [01ROOT].
    let sql = r#"CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at,supersedes_json) VALUES ('01ANC','semantic','user','/a','2025-01-01T00:00:00Z','[]');
INSERT INTO memories_meta(id,kind,subject,path,created_at,supersedes_json) VALUES ('01ROOT','semantic','user','/r','2025-06-01T00:00:00Z','["01ANC"]');
INSERT INTO memories_meta(id,kind,subject,path,created_at,supersedes_json) VALUES ('01NEW','semantic','user','/n','2026-02-01T00:00:00Z','["01ROOT"]');"#;
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-ops");
    let out = Command::new(bin)
        .args(["lineage", "01ROOT", "--format", "json", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let anc: Vec<&str> = json["ancestors"].as_array().unwrap().iter().map(|e| e["id"].as_str().unwrap()).collect();
    let desc: Vec<&str> = json["descendants"].as_array().unwrap().iter().map(|e| e["id"].as_str().unwrap()).collect();
    assert_eq!(anc, vec!["01ANC"], "ancestor walk should find 01ANC");
    assert_eq!(desc, vec!["01NEW"], "descendant walk should find 01NEW");
}
