//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `stats` and `lineage` outputs are byte-identical across consecutive runs on the same fixture. Sorts (by_subject, by_kind keys, lineage entries) are deterministic.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac10() {
    let root = TempDir::new().unwrap();
    fs::create_dir_all(root.path().join("index")).unwrap();
    let db = root.path().join("index").join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01A','semantic','user','/x','2026-01-01T00:00:00Z');
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01B','reflective','self','/y','2026-02-01T00:00:00Z');";
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-ops");
    let run = || {
        Command::new(bin)
            .args(["stats", "--format", "json", "--root"])
            .arg(root.path())
            .output()
            .unwrap()
            .stdout
    };
    let a = run();
    let b = run();
    assert_eq!(a, b, "stats output must be byte-identical");
}
