//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `recall-ops update <id> --confidence <0..1>` updates the row's confidence value in-place. `--body <text>` rewrites the .md body (preserving frontmatter). Exit 1 on unknown id, 0 on success.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac7() {
    let root = TempDir::new().unwrap();
    let mem_path = root.path().join("memories").join("user").join("01A.md");
    fs::create_dir_all(mem_path.parent().unwrap()).unwrap();
    fs::write(&mem_path, "---\nid: 01A\nkind: semantic\n---\noriginal body\n").unwrap();
    fs::create_dir_all(root.path().join("index")).unwrap();
    let db = root.path().join("index").join("recall.sqlite");
    let sql = format!(
        "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at,confidence) VALUES ('01A','semantic','user','{}','2026-01-01T00:00:00Z',0.5);",
        mem_path.display()
    );
    Command::new("sqlite3").arg(&db).arg(&sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-ops");

    // Update confidence.
    let out = Command::new(bin)
        .args(["update", "01A", "--confidence", "0.85", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let conf_raw = Command::new("sqlite3").arg(&db).arg("SELECT confidence FROM memories_meta WHERE id='01A';").output().unwrap();
    let conf: f64 = String::from_utf8(conf_raw.stdout).unwrap().trim().parse().unwrap();
    assert!((conf - 0.85).abs() < 0.001);

    // Update body.
    let out = Command::new(bin)
        .args(["update", "01A", "--body", "new body content", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let new_content = fs::read_to_string(&mem_path).unwrap();
    assert!(new_content.contains("new body content"));
    assert!(new_content.contains("id: 01A"), "frontmatter must be preserved");

    // Unknown id: exit 1.
    let out = Command::new(bin)
        .args(["update", "NOPE", "--confidence", "0.5", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));
}
