//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: All subcommands accept `--root <dir>` (default `~/.claude/recall`). Missing/unreadable root → exit 2 with stderr diagnostic. Missing sqlite3 binary → exit 2.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;
use tempfile::NamedTempFile;

#[test]
fn acceptance_ac8() {
    let bin = env!("CARGO_BIN_EXE_recall-ops");

    // --root that exists but is a file (not dir): exit 2.
    let not_a_dir = NamedTempFile::new().unwrap();
    let out = Command::new(bin)
        .args(["stats", "--root"])
        .arg(not_a_dir.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
    let stderr = String::from_utf8(out.stderr).unwrap();
    assert!(!stderr.is_empty());

    // Missing sqlite3 (PATH override): exit 2.
    let out = Command::new(bin)
        .args(["touch", "01X", "--root"])
        .arg("/tmp/recall-test")
        .env("PATH", "/no/such/path")
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
}
