//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `recall-ops stats [--format text|json]` reports `{total, by_subject: {<subject>: N}, by_kind: {<kind>: N}, oldest_created: <RFC3339 or null>, distinct_embedder_ids: [...]}` from memories_meta. Deterministic JSON output.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac5() {
    let root = TempDir::new().unwrap();
    fs::create_dir_all(root.path().join("index")).unwrap();
    let db = root.path().join("index").join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at,embedding_id) VALUES ('01A','semantic','user','/x','2025-01-01T00:00:00Z','hash-v1');
INSERT INTO memories_meta(id,kind,subject,path,created_at,embedding_id) VALUES ('01B','reflective','self','/y','2025-06-01T00:00:00Z','hash-v1');
INSERT INTO memories_meta(id,kind,subject,path,created_at,embedding_id) VALUES ('01C','semantic','user','/z','2026-02-01T00:00:00Z','bge-v1');";
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-ops");
    let out = Command::new(bin)
        .args(["stats", "--format", "json", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["total"], 3);
    assert_eq!(json["by_subject"]["user"], 2);
    assert_eq!(json["by_subject"]["self"], 1);
    assert_eq!(json["by_kind"]["semantic"], 2);
    assert_eq!(json["by_kind"]["reflective"], 1);
    assert_eq!(json["oldest_created"], "2025-01-01T00:00:00Z");
    let emb: Vec<&str> = json["distinct_embedder_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();
    assert_eq!(emb, vec!["bge-v1", "hash-v1"]);
}
