//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `recall-ops touch <id1> <id2>...` accepts multiple ids; `--format json` returns `{touched: N, results: [{id, new_count, last_recalled_at}, ...]}`. Default text format prints one line per id.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

fn seed(root: &std::path::Path) {
    fs::create_dir_all(root.join("index")).unwrap();
    let db = root.join("index").join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at,recall_count) VALUES ('01A','semantic','user','/tmp/01A.md','2026-01-01T00:00:00Z',0);
INSERT INTO memories_meta(id,kind,subject,path,created_at,recall_count) VALUES ('01B','semantic','user','/tmp/01B.md','2026-01-01T00:00:00Z',3);";
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();
}

#[test]
fn acceptance_ac2() {
    let root = TempDir::new().unwrap();
    seed(root.path());
    let bin = env!("CARGO_BIN_EXE_recall-ops");
    let out = Command::new(bin)
        .args(["touch", "01A", "01B", "--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["touched"], 2);
    let results = json["results"].as_array().unwrap();
    assert_eq!(results.len(), 2);
    assert_eq!(results[0]["id"], "01A");
    assert_eq!(results[1]["id"], "01B");
    assert_eq!(results[0]["new_count"], 1);
    assert_eq!(results[1]["new_count"], 4);

    // Text default emits one line per id.
    let out = Command::new(bin)
        .args(["touch", "01A", "01B", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert_eq!(stdout.lines().filter(|l| l.contains("touched")).count(), 2);
}
