//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `recall-ops gc ... --apply` removes the .md file at memories_meta.path AND deletes the row from memories_meta for each candidate. Reports `{deleted: N, ids: [...]}` in JSON mode. Refuses to run without --older-than to prevent accidental wipe.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac4() {
    let root = TempDir::new().unwrap();
    // Seed: one old file on disk, one fresh.
    fs::create_dir_all(root.path().join("memories").join("user")).unwrap();
    let old_path = root.path().join("memories").join("user").join("01OLD.md");
    fs::write(&old_path, "---\nid: 01OLD\n---\nold body\n").unwrap();
    fs::create_dir_all(root.path().join("index")).unwrap();
    let db = root.path().join("index").join("recall.sqlite");
    let sql = format!(
        "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at,recall_count) VALUES ('01OLD','s','u','{}','2025-01-01T00:00:00Z',0);",
        old_path.display()
    );
    Command::new("sqlite3").arg(&db).arg(&sql).output().unwrap();

    let bin = env!("CARGO_BIN_EXE_recall-ops");
    let out = Command::new(bin)
        .args(["gc", "--older-than", "30d", "--apply", "--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["applied"], true);
    assert_eq!(json["deleted"][0], "01OLD");
    assert!(!old_path.exists(), "file should be deleted from disk");

    // Verify index row gone.
    let out = Command::new("sqlite3")
        .arg(&db)
        .arg("SELECT COUNT(*) FROM memories_meta WHERE id='01OLD';")
        .output()
        .unwrap();
    assert_eq!(String::from_utf8(out.stdout).unwrap().trim(), "0");
}
