//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `recall-ops gc --older-than <duration> [--never-recalled]` lists candidate memory ids matching the predicate (created_at + last_recalled_at older than now-duration; if --never-recalled, also requires recall_count=0). Without --apply, prints candidates and exits 0 (dry-run is default).
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

fn seed_aged(root: &std::path::Path) {
    fs::create_dir_all(root.join("index")).unwrap();
    let db = root.join("index").join("recall.sqlite");
    // Old: 2025-01-01. Fresh: today.
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at,recall_count) VALUES ('01OLD','s','u','/tmp/01OLD.md','2025-01-01T00:00:00Z',0);
INSERT INTO memories_meta(id,kind,subject,path,created_at,recall_count) VALUES ('01FRESH','s','u','/tmp/01FRESH.md','2026-05-23T00:00:00Z',0);";
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();
}

#[test]
fn acceptance_ac3() {
    let root = TempDir::new().unwrap();
    seed_aged(root.path());
    let bin = env!("CARGO_BIN_EXE_recall-ops");
    let out = Command::new(bin)
        .args(["gc", "--older-than", "30d", "--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["applied"], false);
    assert_eq!(json["count"], 1);
    assert_eq!(json["candidates"][0]["id"], "01OLD");
}
