//! Acceptance test for AC9 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: Exit codes: 0 success, 1 expected failure (unknown id, no candidates, dry-run with no matches), 2 invocation error. Stable across runs on identical inputs.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac9() {
    let bin = env!("CARGO_BIN_EXE_recall-ops");

    // 0: success with seeded data.
    let root = TempDir::new().unwrap();
    fs::create_dir_all(root.path().join("index")).unwrap();
    let db = root.path().join("index").join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at) VALUES ('01A','s','u','/x','2026-01-01T00:00:00Z');";
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();
    let out = Command::new(bin).args(["touch", "01A", "--root"]).arg(root.path()).output().unwrap();
    assert_eq!(out.status.code(), Some(0));

    // 1: gc dry-run with no candidates.
    let out = Command::new(bin)
        .args(["gc", "--older-than", "36500d", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));

    // 2: unknown subcommand.
    let out = Command::new(bin).arg("nonsense-sub").output().unwrap();
    assert_eq!(out.status.code(), Some(2));
}
