//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-ops (cli)
//! AC description: `recall-ops touch <id>` bumps `recall_count` by 1 and sets `last_recalled_at` to now (RFC3339) in `memories_meta` for the given id. Exits 0 on success, 1 if the id is unknown.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

fn seed(root: &std::path::Path) {
    fs::create_dir_all(root.join("index")).unwrap();
    let db = root.join("index").join("recall.sqlite");
    let sql = "CREATE TABLE memories_meta (id TEXT PRIMARY KEY, kind TEXT, subject TEXT, path TEXT, confidence REAL DEFAULT 0.5, created_at TEXT, last_recalled_at TEXT, recall_count INTEGER DEFAULT 0, embedding_id TEXT, supersedes_json TEXT);
INSERT INTO memories_meta(id,kind,subject,path,created_at,recall_count) VALUES ('01A','semantic','user','/tmp/01A.md','2026-01-01T00:00:00Z',0);";
    Command::new("sqlite3").arg(&db).arg(sql).output().unwrap();
}

#[test]
fn acceptance_ac1() {
    let root = TempDir::new().unwrap();
    seed(root.path());
    let bin = env!("CARGO_BIN_EXE_recall-ops");

    // Known id: success.
    let out = Command::new(bin)
        .args(["touch", "01A", "--root"])
        .arg(root.path())
        .args(["--format", "json"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(json["touched"], 1);
    assert_eq!(json["results"][0]["new_count"], 1);

    // Verify the DB reflects the bump.
    let db = root.path().join("index").join("recall.sqlite");
    let out = Command::new("sqlite3")
        .arg(&db)
        .arg("SELECT recall_count FROM memories_meta WHERE id='01A';")
        .output()
        .unwrap();
    assert_eq!(String::from_utf8(out.stdout).unwrap().trim(), "1");

    // Unknown id: exit 1.
    let out = Command::new(bin)
        .args(["touch", "NOPE", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(1));
}
