//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: CLI binary `skill` accepts the positional subcommand `validate` followed by a path or skill-name argument. `skill validate <path-to-skill-md>` reads the file, parses its YAML frontmatter, and emits a structured verdict.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const MIN_SKILL_MD: &str = "---\nname: t\ndescription: t\n---\nbody\n";

#[test]
fn acceptance_ac1() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(MIN_SKILL_MD.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");
    let out = Command::new(bin)
        .args(["validate", "--format", "json"])
        .arg(f.path())
        .output()
        .unwrap();

    assert_eq!(
        out.status.code(),
        Some(0),
        "expected exit 0 for valid SKILL.md, stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(!stdout.is_empty(), "expected non-empty stdout");
    let parsed: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert!(parsed.get("verdict").is_some(), "missing verdict key");
}
