//! Acceptance test for AC9 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: `skill validate <skill-name>` (no slash, no `.md` extension) resolves to `~/.claude/skills/<name>/SKILL.md`. If that file doesn't exist, falls back to error path `unknown_skill` with exit code 2.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::fs;
use std::process::Command;
use tempfile::TempDir;

#[test]
fn acceptance_ac9() {
    // Set up a temp HOME with a skill present.
    let temp_home = TempDir::new().unwrap();
    let skill_dir = temp_home.path().join(".claude").join("skills").join("foo-skill");
    fs::create_dir_all(&skill_dir).unwrap();
    let skill_md = skill_dir.join("SKILL.md");
    fs::write(
        &skill_md,
        "---\nname: foo-skill\ndescription: a fixture skill\n---\nbody\n",
    )
    .unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");

    // Bare-name resolution should find the fixture skill.
    let out = Command::new(bin)
        .args(["validate", "--format", "json", "foo-skill"])
        .env("HOME", temp_home.path())
        .output()
        .unwrap();
    assert_eq!(
        out.status.code(),
        Some(0),
        "bare-name resolution failed; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let json: serde_json::Value =
        serde_json::from_str(&String::from_utf8_lossy(&out.stdout)).unwrap();
    assert_eq!(json["verdict"], "pass");

    // Unknown bare name should be exit 2 (invocation error).
    let out = Command::new(bin)
        .args(["validate", "--format", "json", "nonexistent-skill"])
        .env("HOME", temp_home.path())
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
}
