//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: A SKILL.md with no `manifest:` block validates successfully (backwards compatibility). Output: `verdict: pass`, `manifest_present: false`, `warnings: []`. Exit code 0.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const LEGACY_SKILL_MD: &str = "\
---
name: legacy-skill
description: pre-manifest skill, just name+description
---
Just instructions here, no manifest block.
";

#[test]
fn acceptance_ac2() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(LEGACY_SKILL_MD.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");
    let out = Command::new(bin)
        .args(["validate", "--format", "json"])
        .arg(f.path())
        .output()
        .unwrap();

    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(json["verdict"], "pass");
    assert_eq!(json["manifest_present"], false);
}
