//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: Rejects unknown top-level manifest keys (`additionalProperties: false`). Output: `verdict: fail`, error `id: unknown_field`, `path: manifest.<unknown_key>`. Known top-level keys: `version`, `requires`, `exports`, `inputs`, `tests`.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const WITH_UNKNOWN_KEY: &str = "\
---
name: skill
description: t
manifest:
  version: 1.0.0
  bogus_field: oops
---
body
";

#[test]
fn acceptance_ac6() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(WITH_UNKNOWN_KEY.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");
    let out = Command::new(bin)
        .args(["validate", "--format", "json"])
        .arg(f.path())
        .output()
        .unwrap();

    assert_eq!(out.status.code(), Some(1));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(json["verdict"], "fail");
    let errors = json["errors"].as_array().unwrap();
    assert!(
        errors.iter().any(|e| e["id"] == "unknown_field"
            && e["path"] == "manifest.bogus_field"),
        "expected unknown_field error; got {errors:?}"
    );
}
