//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: Malformed YAML frontmatter (truncated, unclosed quote, tab indentation) → `verdict: fail`, error `id: yaml_parse_error` with the underlying parser message. Exit code 1.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const BROKEN_YAML: &str = "\
---
name: broken
description: 'unclosed quote here
manifest:
  version: 1.0.0
---
body
";

#[test]
fn acceptance_ac7() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(BROKEN_YAML.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");
    let out = Command::new(bin)
        .args(["validate", "--format", "json"])
        .arg(f.path())
        .output()
        .unwrap();

    assert_eq!(
        out.status.code(),
        Some(1),
        "expected exit 1 for malformed YAML, stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(json["verdict"], "fail");
    let errors = json["errors"].as_array().unwrap();
    assert!(
        errors.iter().any(|e| e["id"] == "yaml_parse_error"),
        "expected a yaml_parse_error entry; got {errors:?}"
    );
}
