//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: Validates the `manifest.version` field as semver (`^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?$`). Non-semver versions emit `verdict: fail` with error `id: invalid_semver`, `path: manifest.version`, and the offending value. Exit code 1.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

fn write_skill_with_version(version: &str) -> NamedTempFile {
    let mut f = NamedTempFile::new().unwrap();
    let body = format!(
        "---\nname: t\ndescription: t\nmanifest:\n  version: {version}\n---\nbody\n"
    );
    f.write_all(body.as_bytes()).unwrap();
    f.flush().unwrap();
    f
}

fn run(path: &std::path::Path) -> serde_json::Value {
    let bin = env!("CARGO_BIN_EXE_skill");
    let out = Command::new(bin)
        .args(["validate", "--format", "json"])
        .arg(path)
        .output()
        .unwrap();
    let exit = out.status.code();
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
    let parsed: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|_| panic!("bad json (exit={exit:?}): stdout={stdout} stderr={stderr}"));
    parsed
}

#[test]
fn acceptance_ac4() {
    // Valid semvers should pass.
    for ok in ["1.0.0", "0.0.1", "10.20.30", "1.0.0-alpha.1"] {
        let f = write_skill_with_version(ok);
        let bin = env!("CARGO_BIN_EXE_skill");
        let out = Command::new(bin)
            .args(["validate", "--format", "json"])
            .arg(f.path())
            .output()
            .unwrap();
        assert_eq!(out.status.code(), Some(0), "semver {ok} should be accepted");
    }

    // Invalid versions should produce invalid_semver error + exit 1.
    for bad in ["not-a-version", "1.0", "1.0.0.0", "v1.0.0", "1"] {
        let f = write_skill_with_version(&format!("'{bad}'"));
        let bin = env!("CARGO_BIN_EXE_skill");
        let out = Command::new(bin)
            .args(["validate", "--format", "json"])
            .arg(f.path())
            .output()
            .unwrap();
        assert_eq!(out.status.code(), Some(1), "{bad} should fail");
        let json = run(f.path());
        assert_eq!(json["verdict"], "fail");
        let errs = json["errors"].as_array().unwrap();
        assert!(
            errs.iter().any(|e| e["id"] == "invalid_semver" && e["path"] == "manifest.version"),
            "expected invalid_semver error for {bad}; got {errs:?}"
        );
    }
}
