//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: Invocation errors (path does not exist, file unreadable, unknown subcommand) → exit code 2. Stdout is empty; stderr contains a single human-readable diagnostic line. JSON mode emits `{verdict: "error", error: {...}}` to stdout in this case.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::process::Command;

#[test]
fn acceptance_ac8() {
    // Combine three sub-cases into one test: missing-file (text + json) and unknown-subcommand.
    let bin = env!("CARGO_BIN_EXE_skill");

    // Sub-case A: missing file, text mode.
    let out = Command::new(bin)
        .args(["validate", "/nonexistent/path/that/does/not/exist.md"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(!stderr.is_empty(), "expected diagnostic on stderr");

    // Sub-case B: missing file, json mode.
    let out = Command::new(bin)
        .args(["validate", "--format", "json", "/nonexistent/path/x.md"])
        .output()
        .unwrap();
    assert_eq!(out.status.code(), Some(2));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(json["verdict"], "error");

    // Sub-case C: unknown subcommand.
    let out = Command::new(bin).arg("nonsense-subcommand").output().unwrap();
    assert_eq!(out.status.code(), Some(2));
}
