//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: A SKILL.md with a well-formed `manifest:` block (version, requires.binaries, requires.skills, exports, tests — each optional) validates successfully. Output: `verdict: pass`, `manifest_present: true`, with the parsed manifest echoed in the JSON output. Exit code 0.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const SKILL_WITH_MANIFEST: &str = "\
---
name: well-formed-skill
description: A skill with a complete manifest block
manifest:
  version: 1.0.0
  requires:
    binaries:
      - name: ctrace
        version: '>=0.3.0'
      - name: recall
    skills:
      - name: update-config
        version: '>=1.0.0'
      - name: fewer-permission-prompts
        optional: true
  exports:
    - name: run
      description: Execute the full pass
---
Body content.
";

#[test]
fn acceptance_ac3() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(SKILL_WITH_MANIFEST.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");
    let out = Command::new(bin)
        .args(["validate", "--format", "json"])
        .arg(f.path())
        .output()
        .unwrap();

    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(json["verdict"], "pass");
    assert_eq!(json["manifest_present"], true);
    assert!(json["manifest"].is_object(), "manifest echoed in output");
}
