//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: Validates that each entry in `manifest.requires.binaries` has a required `name` field and an optional `version` field (semver-range constraint, e.g. `>=0.3.0`, `>=1.0.0,<2.0.0`). Missing `name` → `verdict: fail`, error `id: missing_required_field`, `path: manifest.requires.binaries[N].name`.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const MISSING_BIN_NAME: &str = "\
---
name: skill
description: t
manifest:
  version: 1.0.0
  requires:
    binaries:
      - version: '>=1.0'
      - name: ctrace
---
body
";

#[test]
fn acceptance_ac5() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(MISSING_BIN_NAME.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");
    let out = Command::new(bin)
        .args(["validate", "--format", "json"])
        .arg(f.path())
        .output()
        .unwrap();

    assert_eq!(out.status.code(), Some(1));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(json["verdict"], "fail");
    let errors = json["errors"].as_array().unwrap();
    assert!(
        errors.iter().any(|e| e["id"] == "missing_required_field"
            && e["path"] == "manifest.requires.binaries[0].name"),
        "expected missing_required_field at binaries[0].name; got {errors:?}"
    );
}
