//! Acceptance test for AC10 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: skill-manifest (cli)
//! AC description: `--format json` (default `text`) emits a single JSON object to stdout matching the schema `skill_manifest.verdict.v1` (verdict, manifest_present, manifest, warnings, errors). Deterministic key ordering; same input always produces byte-identical output.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write as _;
use std::process::Command;
use tempfile::NamedTempFile;

const SKILL_WITH_MANIFEST: &str = "\
---
name: deterministic-skill
description: t
manifest:
  version: 1.0.0
  requires:
    binaries:
      - name: ctrace
        version: '>=0.3.0'
---
body
";

#[test]
fn acceptance_ac10() {
    let mut f = NamedTempFile::new().unwrap();
    f.write_all(SKILL_WITH_MANIFEST.as_bytes()).unwrap();
    f.flush().unwrap();

    let bin = env!("CARGO_BIN_EXE_skill");
    let run = || {
        Command::new(bin)
            .args(["validate", "--format", "json"])
            .arg(f.path())
            .output()
            .unwrap()
            .stdout
    };

    let a = run();
    let b = run();
    let c = run();

    assert_eq!(a, b, "same input must produce byte-identical output (run 1 vs 2)");
    assert_eq!(b, c, "same input must produce byte-identical output (run 2 vs 3)");

    // Top-level shape must include the documented keys.
    let json: serde_json::Value = serde_json::from_slice(&a).unwrap();
    for key in ["verdict", "manifest_present", "warnings", "errors"] {
        assert!(json.get(key).is_some(), "missing required key {key}");
    }
}
